/**
 * D.20 generated and identity columns: snapshot, emit per dialect, diff
 * (in-place where the database allows), validators and render.
 */
import { describe, expect, it } from 'vitest'
import {
  diff,
  emitMysql,
  emitPg,
  emitSqlite,
  extractSnapshot,
  integer,
  numeric,
  renderSchemaSource,
  serial,
  table,
  text,
} from '@forinda/kickjs-db'
import { insertSchema, selectSchema, updateSchema } from '@forinda/kickjs-db/schema'

const orders = table('orders', {
  id: integer().generatedAlwaysAsIdentity().primaryKey(),
  ref: integer().generatedByDefaultAsIdentity(),
  quantity: integer().notNull(),
  price: numeric(12, 2).notNull(),
  total: numeric(12, 2).generatedAlwaysAs('price * quantity'),
  label: text().generatedAlwaysAs("'#' || ref", { stored: false }),
})

const pgEmpty = { version: 1 as const, dialect: 'postgres' as const, tables: {} }

describe('generated and identity columns', () => {
  it('records them in the snapshot, and nothing extra for a plain column', () => {
    const cols = extractSnapshot({ orders }, 'postgres').tables.orders.columns
    expect(cols.id).toMatchObject({ identity: 'always', nullable: false })
    expect(cols.ref.identity).toBe('byDefault')
    expect(cols.total.generated).toEqual({ expression: 'price * quantity', stored: true })
    expect(cols.label.generated).toEqual({ expression: "'#' || ref", stored: false })
    expect(Object.keys(cols.quantity)).toEqual([
      'name',
      'type',
      'nullable',
      'default',
      'primaryKey',
    ])
  })

  it('emits them per dialect', () => {
    const pg = emitPg(diff(pgEmpty, extractSnapshot({ orders }, 'postgres')))
    expect(pg).toContain('"id" integer GENERATED ALWAYS AS IDENTITY NOT NULL')
    expect(pg).toContain('"ref" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL')
    expect(pg).toContain('"total" numeric(12, 2) GENERATED ALWAYS AS (price * quantity) STORED')
    expect(pg).toContain(`"label" text GENERATED ALWAYS AS ('#' || ref) VIRTUAL`)

    const t = table('t', {
      id: serial().primaryKey(),
      a: integer().notNull(),
      twice: integer().generatedAlwaysAs('a * 2'),
    })
    const sqliteTarget = extractSnapshot({ t }, 'sqlite')
    const sqliteEmpty = { version: 1 as const, dialect: 'sqlite' as const, tables: {} }
    expect(
      emitSqlite(diff(sqliteEmpty, sqliteTarget), { from: sqliteEmpty, to: sqliteTarget }),
    ).toContain('"twice" INTEGER GENERATED ALWAYS AS (a * 2) STORED')
    expect(
      emitMysql(
        diff({ version: 1, dialect: 'mysql', tables: {} }, extractSnapshot({ t }, 'mysql')),
      ),
    ).toContain('`twice` INT GENERATED ALWAYS AS (a * 2) STORED')
  })

  it('refuses identity columns off Postgres', () => {
    const t = table('t', { id: integer().generatedAlwaysAsIdentity().primaryKey() })
    expect(() => extractSnapshot({ t }, 'sqlite')).toThrow(/only Postgres has — use serial\(\)/)
  })

  it('changes a generated column in place where Postgres can', () => {
    const v = (total: ReturnType<typeof numeric>) =>
      extractSnapshot(
        {
          o: table('o', {
            id: serial().primaryKey(),
            price: numeric(12, 2),
            total,
          }),
        },
        'postgres',
      )
    const stored = v(numeric(12, 2).generatedAlwaysAs('price * 2'))
    expect(emitPg(diff(stored, v(numeric(12, 2).generatedAlwaysAs('price * 3'))))).toBe(
      'ALTER TABLE "o" ALTER COLUMN "total" SET EXPRESSION AS (price * 3);',
    )
    expect(emitPg(diff(stored, v(numeric(12, 2))))).toBe(
      'ALTER TABLE "o" ALTER COLUMN "total" DROP EXPRESSION;',
    )
    // Becoming generated can't be done in place: re-created.
    expect(emitPg(diff(v(numeric(12, 2)), stored))).toBe(
      'ALTER TABLE "o" DROP COLUMN "total";\nALTER TABLE "o" ADD COLUMN "total" numeric(12, 2) GENERATED ALWAYS AS (price * 2) STORED;',
    )
  })

  it('adds, changes and drops identity', () => {
    const v = (id: ReturnType<typeof integer>) =>
      extractSnapshot({ o: table('o', { id: id.primaryKey() }) }, 'postgres')
    const plain = v(integer())
    const always = v(integer().generatedAlwaysAsIdentity())
    const byDefault = v(integer().generatedByDefaultAsIdentity())
    expect(emitPg(diff(plain, always))).toBe(
      'ALTER TABLE "o" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY;',
    )
    expect(emitPg(diff(always, byDefault))).toBe(
      'ALTER TABLE "o" ALTER COLUMN "id" SET GENERATED BY DEFAULT;',
    )
    expect(emitPg(diff(always, plain))).toBe('ALTER TABLE "o" ALTER COLUMN "id" DROP IDENTITY;')
  })

  it('leaves computed columns out of insert and update validators, not select', () => {
    const insert = insertSchema(orders)
    const parsed = insert.safeParse({ quantity: 2, price: '3.50', total: '99', id: 5 })
    expect(parsed).toEqual({ success: true, data: { quantity: 2, price: '3.50' } })
    expect(Object.keys(updateSchema(orders).toJsonSchema().properties as object)).not.toContain(
      'total',
    )
    expect(Object.keys(selectSchema(orders).toJsonSchema().properties as object)).toContain('total')
  })

  it('renders them back into schema source', () => {
    const src = renderSchemaSource(extractSnapshot({ orders }, 'postgres'))
    expect(src).toContain('integer().primaryKey().generatedAlwaysAsIdentity()')
    expect(src).toContain('integer().notNull().generatedByDefaultAsIdentity()')
    expect(src).toContain(`.generatedAlwaysAs('price * quantity')`)
    expect(src).toContain(`.generatedAlwaysAs("'#' || ref", { stored: false })`)
  })
})
