import { join } from 'node:path'
import { writeFileSafe } from '../utils/fs'
import { toPascalCase, toKebabCase } from '../utils/naming'
import { resolveOutDir } from '../utils/resolve-out-dir'
import type { ProjectPattern } from '../config'

interface GenerateControllerOptions {
  name: string
  outDir?: string
  moduleName?: string
  modulesDir?: string
  pattern?: ProjectPattern
}

export async function generateController(options: GenerateControllerOptions): Promise<string[]> {
  const { name, moduleName, modulesDir, pattern } = options
  const outDir = resolveOutDir({
    type: 'controller',
    outDir: options.outDir,
    moduleName,
    modulesDir,
    defaultDir: 'src/controllers',
    pattern,
  })
  const kebab = toKebabCase(name)
  const pascal = toPascalCase(name)
  const files: string[] = []

  const filePath = join(outDir, `${kebab}.controller.ts`)
  await writeFileSafe(
    filePath,
    `import { Controller, Get, Post, type Ctx } from '@forinda/kickjs'

// \`Ctx<KickRoutes.${pascal}Controller['<method>']>\` is generated by
// \`kick typegen\` (auto-run on \`kick dev\`). After the first run, your IDE
// will autocomplete \`ctx.params\`, \`ctx.body\`, and \`ctx.query\`.
// See https://forinda.github.io/kick-js/guide/typegen for details.

@Controller()
export class ${pascal}Controller {
  // @Autowired() private readonly myService!: MyService

  @Get('/')
  async list(ctx: Ctx<KickRoutes.${pascal}Controller['list']>) {
    ctx.json({ message: '${pascal} list' })
  }

  @Post('/')
  async create(ctx: Ctx<KickRoutes.${pascal}Controller['create']>) {
    ctx.created({ message: '${pascal} created', data: ctx.body })
  }
}
`,
  )
  files.push(filePath)

  return files
}
