import { join } from 'node:path'
import { writeFileSafe } from '../utils/fs'
import { toPascalCase, toKebabCase } from '../utils/naming'
import { resolveOutDir } from '../utils/resolve-out-dir'
import type { ProjectPattern } from '../config'

interface GenerateControllerOptions {
  name: string
  outDir?: string
  moduleName?: string
  modulesDir?: string
  pattern?: ProjectPattern
  pluralize?: boolean
}

export async function generateController(options: GenerateControllerOptions): Promise<string[]> {
  const { name, moduleName, modulesDir, pattern } = options
  const outDir = resolveOutDir({
    type: 'controller',
    outDir: options.outDir,
    moduleName,
    modulesDir,
    defaultDir: 'src/controllers',
    pattern,
    shouldPluralize: options.pluralize ?? true,
  })
  const kebab = toKebabCase(name)
  const pascal = toPascalCase(name)
  const files: string[] = []

  const filePath = join(outDir, `${kebab}.controller.ts`)
  await writeFileSafe(
    filePath,
    `import { Controller, Get, Post, Put, Delete, reply, type Ctx } from '@forinda/kickjs'

// \`Ctx<KickRoutes.${pascal}Controller['<method>']>\` is generated by
// \`kick typegen\` (auto-run on \`kick dev\`). After the first run, your IDE
// will autocomplete \`ctx.params\`, \`ctx.body\`, and \`ctx.query\`.
// See https://kickjs.app/guide/typegen for details.
//
// Return the payload instead of calling \`ctx.json()\` — the runtime sends it,
// and typegen reads the return type to fill in \`KickRoutes[...].response\`.
// \`reply(status, body)\` carries a non-200 status without losing that type.
//
// The bodies below are placeholders: wire them to a service or repository.

@Controller()
export class ${pascal}Controller {
  // @Autowired() private readonly myService!: MyService

  @Get('/')
  async list(ctx: Ctx<KickRoutes.${pascal}Controller['list']>) {
    return { items: [], total: 0 }
  }

  @Get('/:id')
  async getById(ctx: Ctx<KickRoutes.${pascal}Controller['getById']>) {
    return { id: ctx.params.id }
  }

  @Post('/')
  async create(ctx: Ctx<KickRoutes.${pascal}Controller['create']>) {
    return reply.created({ data: ctx.body })
  }

  @Put('/:id')
  async update(ctx: Ctx<KickRoutes.${pascal}Controller['update']>) {
    return { id: ctx.params.id, data: ctx.body }
  }

  @Delete('/:id')
  async remove(ctx: Ctx<KickRoutes.${pascal}Controller['remove']>) {
    return reply.noContent()
  }
}
`,
  )
  files.push(filePath)

  return files
}
