import type { ModuleContext } from './types'
import { generateMinimalModuleIndex } from '../templates'

export async function generateMinimalFiles(ctx: ModuleContext): Promise<void> {
  const { pascal, kebab, plural, style, write } = ctx

  // Module file (named `<kebab>.module.ts` so Vite's module-discovery plugin picks it up)
  await write(`${kebab}.module.ts`, generateMinimalModuleIndex({ pascal, kebab, plural, style }))

  await write(
    `${kebab}.controller.ts`,
    `import { Controller, Get, Post, Put, Delete, reply, type Ctx } from '@forinda/kickjs'

// \`Ctx<KickRoutes.${pascal}Controller['<method>']>\` is generated by
// \`kick typegen\` (auto-run on \`kick dev\`).
//
// Return the payload instead of calling \`ctx.json()\` — the runtime sends it,
// and typegen reads the return type to fill in \`KickRoutes[...].response\`.
// \`reply(status, body)\` carries a non-200 status without losing that type.
//
// The bodies below are placeholders: wire them to a service or repository.
// "Minimal" is about the file count, not the route surface — you get the whole
// CRUD shape here in one file.

@Controller()
export class ${pascal}Controller {
  @Get('/')
  async list(ctx: Ctx<KickRoutes.${pascal}Controller['list']>) {
    return { items: [], total: 0 }
  }

  @Get('/:id')
  async getById(ctx: Ctx<KickRoutes.${pascal}Controller['getById']>) {
    return { id: ctx.params.id }
  }

  @Post('/')
  async create(ctx: Ctx<KickRoutes.${pascal}Controller['create']>) {
    return reply.created({ data: ctx.body })
  }

  @Put('/:id')
  async update(ctx: Ctx<KickRoutes.${pascal}Controller['update']>) {
    return { id: ctx.params.id, data: ctx.body }
  }

  @Delete('/:id')
  async remove(ctx: Ctx<KickRoutes.${pascal}Controller['remove']>) {
    return reply.noContent()
  }
}
`,
  )
}
