import type { ModuleContext } from './types'
import { generateMinimalModuleIndex } from '../templates'

export async function generateMinimalFiles(ctx: ModuleContext): Promise<void> {
  const { pascal, kebab, plural, write } = ctx

  await write('index.ts', generateMinimalModuleIndex({ pascal, kebab, plural }))

  await write(
    `${kebab}.controller.ts`,
    `import { Controller, Get, type Ctx } from '@forinda/kickjs'

// \`Ctx<KickRoutes.${pascal}Controller['<method>']>\` is generated by
// \`kick typegen\` (auto-run on \`kick dev\`).

@Controller()
export class ${pascal}Controller {
  @Get('/')
  async list(ctx: Ctx<KickRoutes.${pascal}Controller['list']>) {
    ctx.json({ message: '${pascal} list' })
  }
}
`,
  )
}
