import type { Request, Response, NextFunction } from 'express'
import {
  parseQuery,
  type QueryFieldConfig,
  type PaginatedResponse,
  type TypedParsedQuery,
} from './query'

/**
 * Augmentable per-request metadata registry.
 *
 * Extend this interface via module augmentation to get type-safe
 * `ctx.get()` / `ctx.set()` across your app. Unknown keys still
 * work with an explicit generic: `ctx.get<MyType>('custom')`.
 *
 * @example
 * ```ts
 * // src/types.ts
 * declare module '@forinda/kickjs' {
 *   interface ContextMeta {
 *     user: { id: string; email: string; roles: string[] }
 *     tenant: { id: string; name: string }
 *     requestStartedAt: number
 *   }
 * }
 *
 * // controller — fully typed, no generics needed
 * ctx.get('user')          // { id: string; email: string; roles: string[] } | undefined
 * ctx.set('tenant', info)  // type-checked value
 * ```
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface ContextMeta {}

/** Resolve a ContextMeta value type, falling back to `Fallback` for unknown keys. */
type MetaValue<K extends string, Fallback = unknown> = K extends keyof ContextMeta
  ? ContextMeta[K]
  : Fallback

/**
 * The shape of a single route entry in `KickRoutes`. Generated by
 * `kick typegen` and consumed via the `Ctx<T>` helper. Each field is
 * `unknown` by default and is filled in as the typegen learns more
 * about the route (URL params from the path, body/query from validation
 * schemas, etc.).
 */
export interface RouteShape {
  params?: unknown
  body?: unknown
  query?: unknown
  response?: unknown
}

/**
 * Unified request/response abstraction passed to every controller method.
 * Shields handlers from raw Express objects and provides convenience methods.
 */
export class RequestContext<TBody = any, TParams = any, TQuery = any> {
  constructor(
    public readonly req: Request,
    public readonly res: Response,
    public readonly next: NextFunction,
  ) {}

  /**
   * Per-request metadata map shared across all RequestContext instances
   * for the same request. Stored on `req` so middleware can pass data
   * to handlers via `ctx.set()` / `ctx.get()`.
   */
  private get metadata(): Map<string, any> {
    const r = this.req as any
    if (!r.__ctxMeta) r.__ctxMeta = new Map<string, any>()
    return r.__ctxMeta
  }

  // ── Request Data ────────────────────────────────────────────────────

  get body(): TBody {
    return this.req.body as TBody
  }

  get params(): TParams {
    return this.req.params as TParams
  }

  get query(): TQuery {
    return this.req.query as TQuery
  }

  get headers() {
    return this.req.headers
  }

  get requestId(): string | undefined {
    return (this.req as any).requestId ?? (this.req.headers['x-request-id'] as string | undefined)
  }

  /** Session data (requires session middleware) */
  get session(): any {
    return (this.req as any).session
  }

  /**
   * The authenticated user set by AuthAdapter.
   * Reads from the per-request metadata store first (`ctx.set('user', ...)`),
   * then falls back to `req.user` (set directly by AuthAdapter middleware).
   *
   * Extend the `AuthUser` interface via module augmentation in `@forinda/kickjs-auth`
   * to get full typing.
   *
   * @example
   * ```ts
   * @Get('/me')
   * @Authenticated()
   * getProfile(ctx: RequestContext) {
   *   const user = ctx.user
   *   if (!user) return ctx.notFound()
   *   return ctx.json({ user })
   * }
   * ```
   */
  get user(): MetaValue<'user', Record<string, any>> | undefined {
    return this.metadata.get('user') ?? (this.req as any).user
  }

  /**
   * Tenant identifier for multi-tenant apps. Reads `user.tenantId` —
   * populated either by `AuthAdapter.testMode({ tenantId })`, a tenant
   * resolver middleware, or manually on the strategy's `mapPayload`.
   *
   * Augment `AuthUser` (or `ContextMeta['user']`) to widen the return
   * type if your user shape guarantees a non-`string | undefined` id.
   */
  get tenantId(): string | undefined {
    const u = this.user as Record<string, any> | undefined
    return u?.tenantId
  }

  /**
   * Effective role list for the current user. Prefers `user.tenantRoles`
   * (populated by `AuthAdapterOptions.roleResolver` under a tenant) and
   * falls back to `user.roles`. Returns an empty array when the user is
   * absent or the shape has neither field.
   */
  get roles(): string[] {
    const u = this.user as Record<string, any> | undefined
    return u?.tenantRoles ?? u?.roles ?? []
  }

  // ── Query String Parsing ───────────────────────────────────────────

  /**
   * Parse the request query string into structured filters, sort, pagination, and search.
   * Pass the result to an ORM query builder adapter (Drizzle, Prisma, Sequelize, etc.).
   *
   * Generic over the field config: when passed an inline literal (or
   * `as const`), `filters[].field` and `sort[].field` are narrowed to
   * the exact whitelisted field names. Pass nothing or a non-literal
   * config and you get the loose `string` fallback.
   *
   * @param fieldConfig - Optional whitelist for filterable, sortable, and searchable fields
   *
   * @example
   * ```ts
   * @Get('/')
   * async list(ctx: RequestContext) {
   *   const parsed = ctx.qs({
   *     filterable: ['status', 'priority'],
   *     sortable: ['createdAt', 'title'],
   *   } as const)
   *   parsed.filters[0].field // typed as 'status' | 'priority'
   *   parsed.sort[0].field    // typed as 'createdAt' | 'title'
   * }
   * ```
   */
  qs<TConfig extends QueryFieldConfig | undefined = undefined>(
    fieldConfig?: TConfig,
  ): TypedParsedQuery<TConfig> {
    return parseQuery<TConfig>(this.req.query as Record<string, any>, fieldConfig)
  }

  // ── File Uploads ────────────────────────────────────────────────────

  /** Single uploaded file (requires @FileUpload({ mode: 'single' })) */
  get file(): any {
    return (this.req as any).file
  }

  /** Array of uploaded files (requires @FileUpload({ mode: 'array' })) */
  get files(): any[] | undefined {
    return (this.req as any).files
  }

  // ── Metadata Store ──────────────────────────────────────────────────

  /**
   * Read a value from the per-request metadata store.
   *
   * When `ContextMeta` has been augmented with a matching key, the return
   * type is inferred automatically. For ad-hoc keys, pass a generic:
   * `ctx.get<MyType>('custom')`.
   */
  get<K extends string>(key: K): MetaValue<K> | undefined {
    return this.metadata.get(key)
  }

  /**
   * Write a value to the per-request metadata store.
   *
   * When `ContextMeta` has been augmented with a matching key, the value
   * type is checked at compile time.
   */
  set<K extends string>(key: K, value: MetaValue<K>): void {
    this.metadata.set(key, value)
  }

  // ── Response Helpers ────────────────────────────────────────────────

  json(data: any, status = 200) {
    return this.res.status(status).json(data)
  }

  created(data: any) {
    return this.res.status(201).json(data)
  }

  noContent() {
    return this.res.status(204).end()
  }

  notFound(message = 'Not Found') {
    return this.res.status(404).json({ message })
  }

  badRequest(message: string) {
    return this.res.status(400).json({ message })
  }

  html(content: string, status = 200) {
    return this.res.status(status).type('html').send(content)
  }

  download(buffer: Buffer, filename: string, contentType = 'application/octet-stream') {
    this.res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
    this.res.setHeader('Content-Type', contentType)
    return this.res.send(buffer)
  }

  /**
   * Render a template using the registered view engine (EJS, Pug, Handlebars, etc.).
   * Requires a ViewAdapter to be configured in bootstrap().
   *
   * @param template - Template name (without extension, relative to viewsDir)
   * @param data - Data to pass to the template
   *
   * @example
   * ```ts
   * ctx.render('dashboard', { user, title: 'Dashboard' })
   * ctx.render('emails/welcome', { name: 'Alice' })
   * ```
   */
  render(template: string, data: Record<string, any> = {}) {
    return this.res.render(template, data)
  }

  /**
   * Parse query params and return a standardized paginated response.
   * Calls `ctx.qs()` internally, then wraps your data with pagination meta.
   *
   * @param fetcher - Async function that receives ParsedQuery and returns `{ data, total }`
   * @param fieldConfig - Optional whitelist for filterable, sortable, searchable fields
   *
   * @example
   * ```ts
   * @Get('/')
   * async list(ctx: RequestContext) {
   *   return ctx.paginate(
   *     async (parsed) => {
   *       const data = await db.select().from(users)
   *         .where(query.where).limit(parsed.pagination.limit)
   *         .offset(parsed.pagination.offset).all()
   *       const total = await db.select({ count: count() }).from(users).get()
   *       return { data, total: total?.count ?? 0 }
   *     },
   *     { filterable: ['name', 'role'], sortable: ['createdAt'] },
   *   )
   * }
   * ```
   */
  async paginate<T, TConfig extends QueryFieldConfig | undefined = undefined>(
    fetcher: (parsed: TypedParsedQuery<TConfig>) => Promise<{ data: T[]; total: number }>,
    fieldConfig?: TConfig,
  ) {
    const parsed = this.qs<TConfig>(fieldConfig)
    const { data, total } = await fetcher(parsed)
    const { page, limit } = parsed.pagination
    const totalPages = Math.ceil(total / limit) || 1

    const response: PaginatedResponse<T> = {
      data,
      meta: {
        page,
        limit,
        total,
        totalPages,
        hasNext: page < totalPages,
        hasPrev: page > 1,
      },
    }

    return this.json(response)
  }

  // ── Server-Sent Events ──────────────────────────────────────────────

  /**
   * Start an SSE (Server-Sent Events) stream.
   * Sets the correct headers and returns helpers to send events.
   *
   * @example
   * ```ts
   * @Get('/events')
   * async stream(ctx: RequestContext) {
   *   const sse = ctx.sse()
   *
   *   const interval = setInterval(() => {
   *     sse.send({ time: new Date().toISOString() }, 'tick')
   *   }, 1000)
   *
   *   sse.onClose(() => clearInterval(interval))
   * }
   * ```
   */
  sse() {
    this.res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      Connection: 'keep-alive',
      'X-Accel-Buffering': 'no',
    })
    this.res.flushHeaders()

    const closeCallbacks: Array<() => void> = []

    this.req.on('close', () => {
      for (const cb of closeCallbacks) cb()
    })

    return {
      /** Send an SSE event with optional event name and id */
      send: (data: any, event?: string, id?: string) => {
        if (id) this.res.write(`id: ${id}\n`)
        if (event) this.res.write(`event: ${event}\n`)
        this.res.write(`data: ${JSON.stringify(data)}\n\n`)
      },
      /** Send a comment (keeps connection alive) */
      comment: (text: string) => {
        this.res.write(`: ${text}\n\n`)
      },
      /** Register a callback when the client disconnects */
      onClose: (fn: () => void) => {
        closeCallbacks.push(fn)
      },
      /** End the SSE stream */
      close: () => {
        this.res.end()
      },
    }
  }
}

/**
 * Short alias for `RequestContext` parameterised by a route shape.
 *
 * Use with `kick typegen`'s generated `KickRoutes` namespace for
 * fully-typed `ctx.params`, `ctx.body`, and `ctx.query`. Metadata
 * typing (`ctx.get()`, `ctx.set()`, `ctx.user`) comes from
 * `ContextMeta` augmentation and works on all `RequestContext` instances.
 *
 * @example
 * ```ts
 * @Get('/:id')
 * getUser(ctx: Ctx<KickRoutes.UserController['getUser']>) {
 *   ctx.params.id      // typed from RouteShape
 *   ctx.body           // typed from RouteShape
 *   ctx.user           // typed from ContextMeta
 *   ctx.get('tenant')  // typed from ContextMeta
 * }
 * ```
 */
export type Ctx<TRoute extends RouteShape = RouteShape> = RequestContext<
  TRoute extends { body: infer B } ? B : any,
  TRoute extends { params: infer P } ? P : any,
  TRoute extends { query: infer Q } ? Q : any
>

/**
 * Global ambient registry of typed routes, populated by `kick typegen`.
 *
 * Each interface inside `KickRoutes` corresponds to a controller class;
 * each property is one route method on that controller. The values
 * conform to `RouteShape`.
 *
 * Empty by default — declarations come from `.kickjs/types/routes.d.ts`
 * generated alongside the rest of the typegen output.
 */
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace KickRoutes {}
}
