/**
 * Emit the self-contained client route map.
 *
 * Everything about this file's shape is in service of one line in an adopter's
 * frontend:
 *
 *     import type { KickApi } from '../../../api/.kickjs/types/kick__client'
 *
 * So: module-scoped (a dts bundler can follow module exports; it cannot follow
 * an ambient global — that is why #543's `rollup-plugin-dts` attempt emitted
 * zero routes), no imports at all (an import is a dependency on the server's
 * program, which is the thing being removed), and hoisted interfaces above the
 * map so 1,940 routes over ~300 shapes stay proportional to the shapes.
 *
 * @module @forinda/kickjs-cli/typegen/render/client
 */
import type { ResolvedClientMap } from '../client/resolve-entries'

const HEADER = `/* eslint-disable */
// AUTO-GENERATED by \`kick typegen\`. DO NOT EDIT.
//
// Self-contained: this file has no imports, so a frontend consumes it without
// compiling the server, its decorators, or its path aliases.
//
//   import type { KickApi } from './path/to/kick__client'
//   export const api = createClient<KickApi>({ baseUrl: '/api/v1' })
//
// Not refreshed by \`kick dev\` — resolving these types builds a full
// TypeScript program over the server. Re-run \`kick typegen\`.
`

export function renderClient(map: ResolvedClientMap, keys: string[]): string {
  const emitted = keys.filter((key) => map.entries.has(key))

  if (emitted.length === 0) {
    return `${HEADER}
// (no routes discovered yet — annotate a controller method with
//  @Get/@Post/@Put/@Delete/@Patch and re-run \`kick typegen\`)
export interface KickApi {}
`
  }

  const hoisted = map.hoisted.length > 0 ? map.hoisted.join('\n\n') + '\n\n' : ''
  const lines = emitted.map((key) => `  ${JSON.stringify(key)}: ${map.entries.get(key)!}`)

  return `${HEADER}
${hoisted}export interface KickApi {
${lines.join('\n')}
}
`
}
