// Pure render module for the `KickEnv` global namespace augmentation
// + `NodeJS.ProcessEnv` narrowing.
//
// Lives outside `generator.ts` so the new `kick/env` typegen plugin
// can call it without importing the legacy generator's monolithic
// `generateTypes()`. Emits as a `.ts` file (not `.d.ts`) for the
// same hoisted-import reason as renderRoutes — bundler moduleResolution
// silently degrades top-level `import type` inside `.d.ts` to
// `unknown`.

import { dirname, relative, sep } from 'node:path'

import type { DiscoveredEnv } from '../scanner'

const ENV_HEADER = `/* eslint-disable */
// AUTO-GENERATED by \`kick typegen\`. DO NOT EDIT.
// Re-run with \`kick typegen\` or rely on \`kick dev\` to refresh.
`

/**
 * Render the `KickEnv` + `NodeJS.ProcessEnv` augmentation file from a
 * detected env schema. Returns `null` when no env file was discovered,
 * so the caller can skip emission entirely (rather than emitting an
 * empty augmentation that would shadow `KickEnv` to a useless `{}`).
 */
export function renderEnv(
  env: DiscoveredEnv | null,
  envOutFile: string,
  schemaValidator: 'zod' | 'kickjs-schema' | false = 'zod',
): string | null {
  if (!env) return null
  // Compute the relative import path from the output file back to the
  // user's env schema source, stripping the extension so TS resolves it.
  const envOutDir = dirname(envOutFile)
  let rel = relative(envOutDir, env.filePath).split(sep).join('/')
  rel = rel.replace(/\.(ts|tsx|mts|cts)$/i, '')
  if (!rel.startsWith('.')) rel = './' + rel

  return `${ENV_HEADER}
// Importing the schema as a type lets us infer its shape without
// pulling in any runtime code. \`Awaited<>\` strips an accidental
// Promise wrap on dynamic-imported defaults.
import type _envSchema from '${rel}'

// Local type alias — interfaces can only \`extend\` an identifier,
// not an inline import expression, so we resolve the schema's
// inferred shape into a named type first.
type _KickEnvShape = ${schemaValidator === 'kickjs-schema' ? "import('@forinda/kickjs-schema').InferSchemaOutput<typeof _envSchema>" : "import('zod').infer<typeof _envSchema>"}

declare global {
  /**
   * Typed environment registry. Augmented from \`${env.relativePath}\`
   * so \`@Value('PORT')\`, \`Env<'PORT'>\`, and \`process.env.PORT\` are
   * all type-safe and autocomplete.
   */
  interface KickEnv extends _KickEnvShape {}

  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace NodeJS {
    /**
     * Narrow \`process.env\` so known keys exist as \`string\` (the raw
     * pre-Zod-coercion form). \`@Value\` and the \`ConfigService\` apply
     * the schema's transforms internally; access \`process.env\` directly
     * only when you need the raw string. Unknown keys still resolve to
     * \`string | undefined\` via the base @types/node declaration.
     */
    interface ProcessEnv extends Record<keyof KickEnv, string> {}
  }
}

export {}
`
}
