/**
 * Pure renderers for the DI-manifest typegen surface — the
 * `KickJsRegistry` augmentation, the `ServiceToken` / `ModuleToken`
 * unions, the `KickJsPluginRegistry` augmentation, and the
 * `defineAugmentation` catalogue.
 *
 * These used to live in `generator.ts` (the monolithic legacy pass).
 * They are now consumed by the per-domain builtin typegen plugins
 * (`kick/registry`, `kick/services`, `kick/modules`, `kick/plugins`,
 * `kick/augmentations`) so the whole pipeline is plugin-based and each
 * file is emitted + cache-tracked independently by the runner.
 *
 * Every function here is pure (scan data in → string out); no fs, no
 * config, no globals.
 *
 * @module @forinda/kickjs-cli/typegen/render/manifest
 */

import { dirname, relative, sep } from 'node:path'
import type {
  ClassCollision,
  DiscoveredAugmentation,
  DiscoveredClass,
  DiscoveredInject,
  DiscoveredPluginOrAdapter,
  DiscoveredToken,
} from '../scanner'

/** Header written to every generated file */
export const HEADER = `/* eslint-disable */
// AUTO-GENERATED by \`kick typegen\`. DO NOT EDIT.
// Re-run with \`kick typegen\` or rely on \`kick dev\` to refresh.
`

/** Decorators whose classes participate in the DI registry augmentation */
export const REGISTRY_DECORATORS = new Set(['Service', 'Repository', 'Injectable', 'Component'])

/** Thrown when collisions are found and not allowed */
export class TokenCollisionError extends Error {
  readonly collisions: ClassCollision[]
  constructor(collisions: ClassCollision[]) {
    super(formatCollisionMessage(collisions))
    this.name = 'TokenCollisionError'
    this.collisions = collisions
  }
}

/** Build a human-readable message describing every collision */
function formatCollisionMessage(collisions: ClassCollision[]): string {
  const lines: string[] = ['kick typegen: token collision detected']
  for (const c of collisions) {
    lines.push('')
    lines.push(`  ${c.classes.length} classes named '${c.className}':`)
    for (const cls of c.classes) {
      lines.push(`    - ${cls.relativePath}`)
    }
  }
  lines.push('')
  lines.push('Resolutions:')
  lines.push('  (a) Rename one of the classes')
  lines.push(
    "  (b) Use createToken<T>('namespaced/Name') and import the token explicitly — see @forinda/kickjs",
  )
  lines.push('  (c) Pass --allow-duplicates to namespace the registry keys automatically')
  lines.push("      (e.g. 'modules/users/UserService' instead of 'UserService')")
  return lines.join('\n')
}

/** Compute the module specifier (without extension) used inside `import('...')` */
function importSpecifierFor(targetFile: string, fromFile: string): string {
  const fromDir = dirname(fromFile)
  let rel = relative(fromDir, targetFile).split(sep).join('/')
  rel = rel.replace(/\.(ts|tsx|mts|cts)$/i, '')
  if (!rel.startsWith('.')) rel = './' + rel
  return rel
}

/**
 * Build the namespaced registry key for a colliding class.
 * Strips the `src/` prefix and the file extension, then appends the
 * class name. Example: `src/modules/users/user.service.ts` + `UserService`
 * → `modules/users/UserService`.
 */
export function namespacedKeyFor(cls: DiscoveredClass): string {
  const rel = cls.relativePath.replace(/^src\//, '').replace(/\.(ts|tsx|mts|cts)$/i, '')
  const parts = rel.split('/')
  parts.pop()
  const ns = parts.join('/')
  return ns ? `${ns}/${cls.className}` : cls.className
}

/**
 * Render the `KickJsRegistry` module augmentation. Each entry maps a
 * string token to the imported class type. Default-exported classes are
 * imported as `import('...').default`. `collidingNames` lists class
 * names that should be auto-namespaced; everything else gets a bare key.
 */
export function renderRegistry(
  classes: DiscoveredClass[],
  outFile: string,
  collidingNames: Set<string>,
): string {
  const seen = new Set<string>()
  const entries: string[] = []

  for (const c of classes) {
    if (!REGISTRY_DECORATORS.has(c.decorator)) continue

    const key = collidingNames.has(c.className) ? namespacedKeyFor(c) : c.className
    if (seen.has(key)) continue
    seen.add(key)

    const spec = importSpecifierFor(c.filePath, outFile)
    const ref = c.isDefault ? `import('${spec}').default` : `import('${spec}').${c.className}`
    entries.push(`    '${key}': ${ref}`)
  }

  const body = entries.length
    ? entries.join('\n')
    : '    // (no services discovered yet — run `kick g service <name>` to add one)'

  return `${HEADER}
declare module '@forinda/kickjs' {
  interface KickJsRegistry {
${body}
  }
}

export {}
`
}

/** True when `str` is a bare JS identifier (usable as an unquoted key). */
function isIdentifierKey(str: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(str)
}

/**
 * Render the `ContextKeys` augmentation from discovered context-decorator
 * keys. Each `key:` literal becomes a `'<key>': true` entry — a key-only
 * registry (the value type is irrelevant; `true` is conventional) so
 * `dependsOn: ['<key>']` is autocompleted + typo-checked without forcing
 * a value type into `ContextMeta`. Non-identifier keys are quoted.
 */
export function renderContextKeys(keys: readonly { key: string }[]): string {
  const unique = [...new Set(keys.map((k) => k.key))].toSorted()
  const body = unique
    .map((k) => `    ${isIdentifierKey(k) ? k : JSON.stringify(k)}: true`)
    .join('\n')
  return `${HEADER}
declare module '@forinda/kickjs' {
  /**
   * Key-only registry of every context key produced by a
   * \`defineContextDecorator\` / \`defineHttpContextDecorator\` in the
   * project. Feeds \`dependsOn\` typo-checking. Value types live in
   * \`ContextMeta\`; this only records that the key exists.
   */
  interface ContextKeys {
${body}
  }
}

export {}
`
}

/** Render a string-literal union type containing the given names */
export function renderUnion(typeName: string, names: string[], emptyComment: string): string {
  if (names.length === 0) {
    return `${HEADER}
// ${emptyComment}
export type ${typeName} = never
`
  }
  const sorted = [...new Set(names)].toSorted()
  return `${HEADER}
export type ${typeName} =
${sorted.map((n) => `  | '${n}'`).join('\n')}
`
}

/**
 * Build the `ServiceToken` union members — class names (namespaced on
 * collision), plus `createToken('name')` and `@Inject('literal')`
 * literals — so tooling autocomplete sees every known token.
 */
export function buildServiceTokens(
  classes: DiscoveredClass[],
  tokens: DiscoveredToken[],
  injects: DiscoveredInject[],
  collidingNames: Set<string>,
): string[] {
  const classTokens = classes
    .filter((c) => REGISTRY_DECORATORS.has(c.decorator))
    .map((c) => (collidingNames.has(c.className) ? namespacedKeyFor(c) : c.className))
  return [...classTokens, ...tokens.map((t) => t.name), ...injects.map((i) => i.name)]
}

/** Build the `ModuleToken` union members — discovered `@Module` class names. */
export function buildModuleTokens(classes: DiscoveredClass[]): string[] {
  return classes.filter((c) => c.decorator === 'Module').map((c) => c.className)
}

/**
 * Render the `KickJsPluginRegistry` augmentation. Each entry maps the
 * literal `name` field of a plugin/adapter to a marker type (the
 * registry value isn't load-bearing at runtime — `dependsOn` only cares
 * about `keyof`, so any non-`never` type works). We emit `'plugin'` /
 * `'adapter'` strings so DevTools can later read the registry to tell
 * the kinds apart without a second source of truth.
 *
 * When the project has no discoverable plugins/adapters, the
 * augmentation is intentionally empty rather than skipped so the
 * `keyof` constraint resolves to `never` (harmless — `dependsOn: []`
 * still works).
 */
export function renderPlugins(items: DiscoveredPluginOrAdapter[]): string {
  // Dedupe by name — two declarations with the same name are a runtime
  // boot-time error in `mount-sort.ts`; we surface the conflict via a
  // single registry entry rather than a duplicate-key TS error.
  const byName = new Map<string, DiscoveredPluginOrAdapter>()
  for (const item of items) {
    if (!byName.has(item.name)) byName.set(item.name, item)
  }

  const sorted = [...byName.values()].toSorted((a, b) => a.name.localeCompare(b.name))
  const entries = sorted.map((item) => `    '${item.name}': '${item.kind}'`).join('\n')

  const body = entries
    ? entries
    : '    // (no plugins/adapters discovered yet — `defineAdapter`/`definePlugin` calls feed this)'

  return `${HEADER}
declare module '@forinda/kickjs' {
  /**
   * Map of every plugin/adapter \`name\` discovered in the project. The
   * value type is the kind tag (\`'plugin'\` or \`'adapter'\`); the
   * \`keyof\` of this interface narrows \`dependsOn\` so misspelled deps
   * become compile errors instead of boot-time \`MissingMountDepError\`.
   */
  interface KickJsPluginRegistry {
${body}
  }
}

export {}
`
}

/**
 * Render the augmentation manifest — one block per `defineAugmentation`
 * call discovered in the project. The output is a `.d.ts` file that does
 * nothing at runtime but acts as in-IDE documentation.
 */
export function renderAugmentations(items: DiscoveredAugmentation[]): string {
  if (items.length === 0) {
    return `${HEADER}
// No augmentations discovered.
//
// Plugins advertise augmentable interfaces via:
//
//   import { defineAugmentation } from '@forinda/kickjs'
//   defineAugmentation('FeatureFlags', {
//     description: 'Feature flag shape consumed by FlagsPlugin',
//     example: '{ beta: boolean; rolloutPercentage: number }',
//   })
//
// See \`docs/guide/typegen.md#augmentations\` for the full pattern.
export {}
`
  }

  // Dedupe by name — multiple plugins shouldn't claim the same name,
  // but if they do we keep the first.
  const byName = new Map<string, DiscoveredAugmentation>()
  for (const item of items) {
    if (!byName.has(item.name)) byName.set(item.name, item)
  }

  const blocks: string[] = []
  for (const item of [...byName.values()].toSorted((a, b) => a.name.localeCompare(b.name))) {
    const docLines: string[] = []
    if (item.description) {
      for (const line of item.description.split('\n')) docLines.push(` * ${line}`)
    }
    if (item.example) {
      docLines.push(` * @example`, ` * \`\`\`ts`)
      for (const line of item.example.split('\n')) docLines.push(` * ${line}`)
      docLines.push(` * \`\`\``)
    }
    docLines.push(` * @see ${item.relativePath}`)
    blocks.push(
      ['/**', ...docLines, ' */', `export interface ${item.name}Augmentation {}`].join('\n'),
    )
  }

  return `${HEADER}
// Catalogue of augmentable interfaces in this project. The interfaces
// below are documentation only — augment the source-of-truth interfaces
// in your own \`d.ts\` files (the framework declares the actual types).

${blocks.join('\n\n')}
`
}
