// Pure render module for the `KickRoutes` global namespace augmentation.
//
// Lives outside `generator.ts` so the new `kick/routes` typegen plugin
// can call it without importing the legacy generator's monolithic
// `generateTypes()`. Functionally identical to what `generator.ts`
// emitted before the M2.B-T8 carve — same hoisted-import strategy,
// same per-controller interface layout, same query-shape inference.
//
// The header banner is the plugin runner's responsibility (see
// `runTypegen` in ../runner.ts), not this module's. Keep `renderRoutes`
// returning just the augmentation source so the plugin doesn't
// double-emit the boilerplate.

import { dirname, relative, resolve, sep } from 'node:path'

import type { DiscoveredRoute } from '../scanner'

const ROUTES_HEADER = `/* eslint-disable */
// AUTO-GENERATED by \`kick typegen\`. DO NOT EDIT.
// Re-run with \`kick typegen\` or rely on \`kick dev\` to refresh.
`

/**
 * Render the `KickRoutes` global namespace augmentation. Each interface
 * inside corresponds to a controller class; each property is a single
 * route method on that controller, conforming to `RouteShape`.
 *
 * Fills `params` from URL patterns, `query` from `@ApiQueryParams`, and
 * `body`/`query`/`params` (when schema-validated) from the configured
 * schema validator. `response` is emitted as `unknown`.
 */
export function renderRoutes(
  routes: DiscoveredRoute[],
  routesOutFile: string,
  schemaValidator: 'zod' | 'kickjs-schema' | false,
  opts: { onWarn?: (msg: string) => void } = {},
): string {
  if (routes.length === 0) {
    return `${ROUTES_HEADER}
// (no routes discovered yet — annotate a controller method with
//  @Get/@Post/@Put/@Delete/@Patch and re-run \`kick typegen\`)
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace KickRoutes {
    // Always present so \`createClient<KickRoutes.Api>\` compiles before the
    // first route exists (fresh project / pre-controller typegen runs).
    interface Api {}
  }

  /** Short alias for \`KickRoutes.Api\` — \`createClient<KickApi>(...)\`. */
  type KickApi = KickRoutes.Api
}

export {}
`
  }

  // Group routes by controller for emission
  const byController = new Map<string, DiscoveredRoute[]>()
  for (const r of routes) {
    const arr = byController.get(r.controller) ?? []
    arr.push(r)
    byController.set(r.controller, arr)
  }

  // Hoisted schema imports — collected during interface rendering, then
  // emitted at the top of `routes.ts` so the in-namespace type references
  // resolve correctly. (Inline `import('...').X` inside `.d.ts` files
  // silently degrades to `unknown` with `moduleResolution: 'bundler'`.)
  const schemaImports = new Map<string, { identifier: string; specifier: string }>()

  // Hoisted controller type imports for response inference — one alias per
  // (file, class). The consumer's tsc computes the response from the
  // handler's return type via InferHandlerResponse; the scanner never runs
  // a type checker (response-inference-design.md R2).
  const controllerImports = new Map<string, string>()
  const planControllerImport = (m: DiscoveredRoute): string => {
    const key = `${m.filePath}::${m.controller}`
    let alias = controllerImports.get(key)
    if (!alias) {
      alias = `_C${controllerImports.size}`
      controllerImports.set(key, alias)
    }
    return alias
  }

  const renderField = (
    schema: { identifier: string; source: string | null } | null,
    m: DiscoveredRoute,
    field: 'body' | 'query' | 'params' | 'response',
  ): string | null => {
    const alias = planSchemaImport(
      schema,
      m.filePath,
      routesOutFile,
      schemaValidator,
      schemaImports,
    )
    if (!alias) {
      // The adopter wired a schema but we couldn't link it — the emitted
      // type silently degrades, so say so. A disabled validator is an
      // intentional opt-out and stays quiet.
      if (schema && schemaValidator !== false) {
        // Name the ACTUAL fallback per field: params → URL-pattern params,
        // query → the @ApiQueryParams-derived shape when one exists
        // (renderQueryShape), otherwise 'unknown'.
        const fallback =
          field === 'params'
            ? 'URL-pattern params'
            : field === 'query' && m.queryFilterable !== null
              ? 'the @ApiQueryParams-derived query shape'
              : `'unknown'`
        opts.onWarn?.(
          `route ${m.controller}.${m.method} (${m.httpMethod} ${m.path}): ` +
            `${field} schema '${schema.identifier}' could not be statically resolved — ` +
            `falling back to ${fallback}. ` +
            `Export the schema from the controller file or import it with a static specifier.`,
        )
      }
      return null
    }
    if (schemaValidator === 'kickjs-schema') {
      return `import('@forinda/kickjs-schema').InferSchemaOutput<typeof ${alias}>`
    }
    return `import('zod').infer<typeof ${alias}>`
  }

  const interfaces: string[] = []
  for (const [controller, methods] of byController) {
    const lines: string[] = [`    interface ${controller} {`]
    for (const m of methods) {
      // Empty `{}` (rather than `Record<string, never>`) so that accessing
      // an unknown property on a paramless route is a type error in strict
      // mode. `Record<string, never>` returns `never` for any access which
      // unfortunately is assignable to anything and silently passes.
      const urlParamsType =
        m.pathParams.length > 0 ? `{ ${m.pathParams.map((p) => `${p}: string`).join('; ')} }` : '{}'

      // Schema-driven types win over the URL-pattern / `unknown` defaults
      // when the user has wired a schema in the route decorator.
      const bodySchemaType = renderField(m.bodySchema, m, 'body')
      const querySchemaType = renderField(m.querySchema, m, 'query')
      const paramsSchemaType = renderField(m.paramsSchema, m, 'params')

      const paramsType = paramsSchemaType ?? urlParamsType
      const bodyType = bodySchemaType ?? 'unknown'
      const queryType = querySchemaType ?? renderQueryShape(m)
      // Response type, priority order:
      //   1. Declared contract (`@Get('/', { response: schema })`) — the
      //      schema's inferred type; same declaration feeds Swagger.
      //   2. Return-type inference via InferHandlerResponse (return-value
      //      handlers exact; imperative ctx.json degrades to unknown).
      const responseSchemaType = renderField(m.responseSchema ?? null, m, 'response')
      const controllerAlias = planControllerImport(m)
      const responseType =
        responseSchemaType ??
        `import('@forinda/kickjs').InferHandlerResponse<${controllerAlias}['${m.method}']>`
      const docLines = renderQueryDocLines(m)
      lines.push(
        `      /**`,
        `       * ${m.httpMethod} ${m.path}`,
        ...docLines.map((d) => `       * ${d}`),
        `       */`,
        `      ${m.method}: {`,
        `        params: ${paramsType}`,
        `        body: ${bodyType}`,
        `        query: ${queryType}`,
        `        response: ${responseType}`,
        `      }`,
      )
    }
    lines.push('    }')
    interfaces.push(lines.join('\n'))
  }

  // Flat verb+path map for the typed client (`@forinda/kickjs-client`):
  // `KickRoutes.Api['GET /users/:id']` → the same shape as the controller
  // interface entry (referenced, not duplicated). Paths are module-mount
  // relative — the client's `baseUrl` carries the bootstrap-level
  // `/api/v{n}` prefix, which is not statically scannable.
  const apiEntries: string[] = []
  const seenApiKeys = new Set<string>()
  // 'Api' is reserved for the flat map below — a user controller class named
  // Api would declaration-merge its methods into the client map silently.
  if (byController.has('Api')) {
    opts.onWarn?.(
      `controller class 'Api' collides with the reserved KickRoutes.Api client map — ` +
        `its interface declaration-merges into the flat route map. Rename the controller.`,
    )
  }
  for (const [controller, methods] of byController) {
    for (const m of methods) {
      // Mount-joined path — the bare decorator path would collide across
      // controllers ('GET /:id' everywhere) and 404 against real URLs.
      const key = `${m.httpMethod} ${m.mountedPath ?? m.path}`
      if (seenApiKeys.has(key)) {
        opts.onWarn?.(
          `duplicate route '${key}' (${controller}.${m.method}) — two handlers claim the same ` +
            `verb+path at runtime. KickRoutes.Api keeps the first (scan order, which may not match ` +
            `runtime dispatch); resolve the conflict in the modules.`,
        )
        continue
      }
      seenApiKeys.add(key)
      apiEntries.push(`      '${key}': ${controller}['${m.method}']`)
    }
  }
  const apiInterface = [`    interface Api {`, ...apiEntries, `    }`].join('\n')
  interfaces.push(apiInterface)

  // Controller type imports — same hoisting rationale as schema imports.
  // `source: ''` semantics of resolveSchemaImportSpecifier point the
  // specifier at the controller file itself.
  const controllerImportLines: string[] = []
  const routeByKey = new Map<string, DiscoveredRoute>()
  for (const r of routes) routeByKey.set(`${r.filePath}::${r.controller}`, r)
  for (const [key, alias] of controllerImports) {
    const route = routeByKey.get(key)!
    const specifier = resolveSchemaImportSpecifier('', route.filePath, routesOutFile)
    const binding = route.controllerIsDefaultExport
      ? `default as ${alias}`
      : `${route.controller} as ${alias}`
    controllerImportLines.push(`import type { ${binding} } from '${specifier}'`)
  }
  const controllerImportBlock =
    controllerImportLines.length > 0 ? controllerImportLines.join('\n') + '\n' : ''

  const importBlock = renderSchemaImports(schemaImports) + controllerImportBlock
  const interfaceBlock = interfaces.join('\n')

  return `${ROUTES_HEADER}${importBlock}
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace KickRoutes {
${interfaceBlock}
  }

  /** Short alias for \`KickRoutes.Api\` — \`createClient<KickApi>(...)\`. */
  type KickApi = KickRoutes.Api
}

export {}
`
}

// ── Helpers ─────────────────────────────────────────────────────────

function renderQueryShape(m: DiscoveredRoute): string {
  if (m.queryFilterable === null) return 'unknown'
  const sortable = m.querySortable ?? []
  const sortType =
    sortable.length > 0 ? sortable.flatMap((f) => [`'${f}'`, `'-${f}'`]).join(' | ') : 'string'
  return `{ filter?: string | string[]; sort?: ${sortType}; q?: string; page?: string; limit?: string }`
}

function renderQueryDocLines(m: DiscoveredRoute): string[] {
  const lines: string[] = []
  if (m.queryFilterable && m.queryFilterable.length > 0) {
    lines.push(`Filterable: ${m.queryFilterable.join(', ')}`)
  }
  if (m.querySortable && m.querySortable.length > 0) {
    lines.push(`Sortable: ${m.querySortable.join(', ')}`)
  }
  if (m.querySearchable && m.querySearchable.length > 0) {
    lines.push(`Searchable: ${m.querySearchable.join(', ')}`)
  }
  return lines
}

/**
 * Plan a schema import for hoisting at the top of `routes.ts`. Returns
 * the alias the in-namespace code should use, or `null` if the schema
 * cannot be referenced (no validator configured, or source unresolvable).
 */
function planSchemaImport(
  schema: { identifier: string; source: string | null } | null,
  routeFilePath: string,
  routesOutFile: string,
  schemaValidator: 'zod' | 'kickjs-schema' | false,
  imports: Map<string, { identifier: string; specifier: string }>,
): string | null {
  if (!schema || schemaValidator === false) return null
  if (schema.source === null) return null
  const specifier = resolveSchemaImportSpecifier(schema.source, routeFilePath, routesOutFile)
  if (specifier === 'unknown') return null
  const key = `${specifier}::${schema.identifier}`
  let alias = imports.get(key)?.specifier
  if (!alias) {
    alias = `_S${imports.size}`
    imports.set(key, { identifier: schema.identifier, specifier: alias })
  } else {
    alias = imports.get(key)!.specifier
  }
  return alias
}

function renderSchemaImports(
  imports: Map<string, { identifier: string; specifier: string }>,
): string {
  if (imports.size === 0) return ''
  const lines: string[] = []
  for (const [key, value] of imports) {
    const [path] = key.split('::')
    lines.push(`import type { ${value.identifier} as ${value.specifier} } from '${path}'`)
  }
  return lines.join('\n') + '\n'
}

/**
 * Compute the import specifier the generated `routes.d.ts` should use
 * to reach a schema declared either in the controller file (empty
 * string) or imported from elsewhere (relative path or bare module).
 */
function resolveSchemaImportSpecifier(
  source: string | null,
  routeFilePath: string,
  routesOutFile: string,
): string {
  if (source === null) return 'unknown'
  const routesDir = dirname(routesOutFile)

  // Same-file schema — point at the controller file itself
  if (source === '') {
    let rel = relative(routesDir, routeFilePath).split(sep).join('/')
    rel = rel.replace(/\.(ts|tsx|mts|cts)$/i, '')
    if (!rel.startsWith('.')) rel = './' + rel
    return rel
  }

  // Bare module name (no leading `.` and not absolute) → keep as-is
  if (!source.startsWith('.') && !source.startsWith('/')) {
    return source
  }

  // Relative import → resolve against the controller's directory, then
  // re-relativise against the routes.d.ts directory
  const controllerDir = dirname(routeFilePath)
  const absoluteTarget = resolve(controllerDir, source)
  let rel = relative(routesDir, absoluteTarget).split(sep).join('/')
  rel = rel.replace(/\.(ts|tsx|mts|cts)$/i, '')
  if (!rel.startsWith('.')) rel = './' + rel
  return rel
}
