import type { TemplateContext } from './types'

/** DDD controller — injects use-cases, nested import paths */
export function generateController(ctx: TemplateContext): string {
  const { pascal, kebab, plural = '', pluralPascal = '' } = ctx
  // Wrapped exactly as oxfmt would at the scaffold's printWidth of 100 —
  // a single-line import is 112 chars, so `kick format` on a fresh project
  // would otherwise rewrite this file on the adopter's first run.
  return `import {
  Controller,
  Get,
  Post,
  Put,
  Delete,
  Autowired,
  ApiQueryParams,
  reply,
  type Ctx,
} from '@forinda/kickjs'
import { ApiTags } from '@forinda/kickjs-swagger'
import { Create${pascal}UseCase } from '../application/use-cases/create-${kebab}.use-case'
import { Get${pascal}UseCase } from '../application/use-cases/get-${kebab}.use-case'
import { List${pluralPascal}UseCase } from '../application/use-cases/list-${plural}.use-case'
import { Update${pascal}UseCase } from '../application/use-cases/update-${kebab}.use-case'
import { Delete${pascal}UseCase } from '../application/use-cases/delete-${kebab}.use-case'
import { create${pascal}Schema } from '../application/dtos/create-${kebab}.dto'
import { update${pascal}Schema } from '../application/dtos/update-${kebab}.dto'
import { ${pascal.toUpperCase()}_QUERY_CONFIG } from '../constants'

// Each handler annotates its \`ctx\` with \`Ctx<KickRoutes.${pascal}Controller['<method>']>\`
// so \`ctx.params\`, \`ctx.body\`, and \`ctx.query\` are typed end-to-end.
// The \`KickRoutes\` namespace is generated by \`kick typegen\` (auto-run on
// \`kick dev\`) — see https://kickjs.app/guide/typegen.
//
// Handlers RETURN their payload rather than calling \`ctx.json()\`: the runtime
// auto-sends it, and \`kick typegen\` reads the return type to fill in
// \`KickRoutes[...].response\` — which is what makes the typed client know what
// each route gives back. A handler that writes via \`ctx.json()\` and returns
// nothing infers as \`unknown\`. Use \`reply(status, body)\` (or the
// \`reply.created\` / \`reply.noContent\` sugars) when the status isn't 200, and
// \`ctx.problem.*\` for error branches — those send immediately and return
// nothing, so they stay out of the success type.

@Controller()
export class ${pascal}Controller {
  @Autowired() private readonly create${pascal}UseCase!: Create${pascal}UseCase
  @Autowired() private readonly get${pascal}UseCase!: Get${pascal}UseCase
  @Autowired() private readonly list${pluralPascal}UseCase!: List${pluralPascal}UseCase
  @Autowired() private readonly update${pascal}UseCase!: Update${pascal}UseCase
  @Autowired() private readonly delete${pascal}UseCase!: Delete${pascal}UseCase

  @Get('/')
  @ApiTags('${pascal}')
  @ApiQueryParams(${pascal.toUpperCase()}_QUERY_CONFIG)
  async list(ctx: Ctx<KickRoutes.${pascal}Controller['list']>) {
    return ctx.paginate(
      (parsed) => this.list${pluralPascal}UseCase.execute(parsed),
      ${pascal.toUpperCase()}_QUERY_CONFIG,
    )
  }

  @Get('/:id')
  @ApiTags('${pascal}')
  async getById(ctx: Ctx<KickRoutes.${pascal}Controller['getById']>) {
    const result = await this.get${pascal}UseCase.execute(ctx.params.id)
    if (!result) {
      // Sends RFC 9457 problem+json now; returning nothing keeps the 404 out
      // of this route's inferred response type.
      ctx.problem.notFound({ detail: \`${pascal} \${ctx.params.id} not found\` })
      return
    }
    return result
  }

  @Post('/', { body: create${pascal}Schema, name: 'Create${pascal}' })
  @ApiTags('${pascal}')
  async create(ctx: Ctx<KickRoutes.${pascal}Controller['create']>) {
    return reply.created(await this.create${pascal}UseCase.execute(ctx.body))
  }

  @Put('/:id', { body: update${pascal}Schema, name: 'Update${pascal}' })
  @ApiTags('${pascal}')
  async update(ctx: Ctx<KickRoutes.${pascal}Controller['update']>) {
    return this.update${pascal}UseCase.execute(ctx.params.id, ctx.body)
  }

  @Delete('/:id')
  @ApiTags('${pascal}')
  async remove(ctx: Ctx<KickRoutes.${pascal}Controller['remove']>) {
    await this.delete${pascal}UseCase.execute(ctx.params.id)
    return reply.noContent()
  }
}
`
}

/** REST controller — injects service directly, flat import paths */
export function generateRestController(ctx: TemplateContext): string {
  const { pascal, kebab } = ctx
  const camel = pascal.charAt(0).toLowerCase() + pascal.slice(1)
  // Wrapped exactly as oxfmt would at the scaffold's printWidth of 100 —
  // a single-line import is 112 chars, so `kick format` on a fresh project
  // would otherwise rewrite this file on the adopter's first run.
  return `import {
  Controller,
  Get,
  Post,
  Put,
  Delete,
  Autowired,
  ApiQueryParams,
  reply,
  type Ctx,
} from '@forinda/kickjs'
import { ApiTags } from '@forinda/kickjs-swagger'
import { ${pascal}Service } from './${kebab}.service'
import { create${pascal}Schema } from './dtos/create-${kebab}.dto'
import { update${pascal}Schema } from './dtos/update-${kebab}.dto'
import { ${pascal.toUpperCase()}_QUERY_CONFIG } from './${kebab}.constants'

// Each handler annotates its \`ctx\` with \`Ctx<KickRoutes.${pascal}Controller['<method>']>\`
// so \`ctx.params\`, \`ctx.body\`, and \`ctx.query\` are typed end-to-end.
// The \`KickRoutes\` namespace is generated by \`kick typegen\` (auto-run on
// \`kick dev\`) — see https://kickjs.app/guide/typegen.
//
// Handlers RETURN their payload rather than calling \`ctx.json()\`: the runtime
// auto-sends it, and \`kick typegen\` reads the return type to fill in
// \`KickRoutes[...].response\` — which is what makes the typed client know what
// each route gives back. A handler that writes via \`ctx.json()\` and returns
// nothing infers as \`unknown\`. Use \`reply(status, body)\` (or the
// \`reply.created\` / \`reply.noContent\` sugars) when the status isn't 200, and
// \`ctx.problem.*\` for error branches — those send immediately and return
// nothing, so they stay out of the success type.

@Controller()
export class ${pascal}Controller {
  @Autowired() private readonly ${camel}Service!: ${pascal}Service

  @Get('/')
  @ApiTags('${pascal}')
  @ApiQueryParams(${pascal.toUpperCase()}_QUERY_CONFIG)
  async list(ctx: Ctx<KickRoutes.${pascal}Controller['list']>) {
    return ctx.paginate(
      (parsed) => this.${camel}Service.findPaginated(parsed),
      ${pascal.toUpperCase()}_QUERY_CONFIG,
    )
  }

  @Get('/:id')
  @ApiTags('${pascal}')
  async getById(ctx: Ctx<KickRoutes.${pascal}Controller['getById']>) {
    const result = await this.${camel}Service.findById(ctx.params.id)
    if (!result) {
      // Sends RFC 9457 problem+json now; returning nothing keeps the 404 out
      // of this route's inferred response type.
      ctx.problem.notFound({ detail: \`${pascal} \${ctx.params.id} not found\` })
      return
    }
    return result
  }

  @Post('/', { body: create${pascal}Schema, name: 'Create${pascal}' })
  @ApiTags('${pascal}')
  async create(ctx: Ctx<KickRoutes.${pascal}Controller['create']>) {
    return reply.created(await this.${camel}Service.create(ctx.body))
  }

  @Put('/:id', { body: update${pascal}Schema, name: 'Update${pascal}' })
  @ApiTags('${pascal}')
  async update(ctx: Ctx<KickRoutes.${pascal}Controller['update']>) {
    return this.${camel}Service.update(ctx.params.id, ctx.body)
  }

  @Delete('/:id')
  @ApiTags('${pascal}')
  async remove(ctx: Ctx<KickRoutes.${pascal}Controller['remove']>) {
    await this.${camel}Service.delete(ctx.params.id)
    return reply.noContent()
  }
}
`
}
