import { Controller, Get, Autowired, ConfigService, type Ctx } from '@forinda/kickjs'
import { HelloService } from './hello.service'

// `Ctx<KickRoutes.HelloController['<method>']>` is generated by
// `kick typegen` (auto-run on `kick dev`). The first run after a fresh
// scaffold creates `.kickjs/types/routes.ts` so this file typechecks.
// See https://forinda.github.io/kick-js/guide/typegen.

@Controller()
export class HelloController {
  @Autowired() private readonly helloService!: HelloService
  @Autowired() private readonly config!: ConfigService

  @Get('/')
  index(ctx: Ctx<KickRoutes.HelloController['index']>) {
    // Pull user-defined env keys straight off the injected ConfigService.
    // `APP_NAME` and `APP_GREETING` are declared in `src/env.ts` and
    // sourced from `.env` via the optional dotenv peer.
    const appName = this.config.get('APP_NAME')
    const greeting = this.config.get('APP_GREETING')

    ctx.json({
      ...this.helloService.greet(appName),
      greeting,
      env: {
        port: this.config.get('PORT'),
        nodeEnv: this.config.get('NODE_ENV'),
        appName,
      },
    })
  }

  @Get('/health')
  health(ctx: Ctx<KickRoutes.HelloController['health']>) {
    ctx.json({
      ...this.helloService.healthCheck(),
      app: this.config.get('APP_NAME'),
      mode: this.config.isProduction() ? 'production' : 'development',
    })
  }
}
