import { Controller, Get, Autowired, type Ctx } from '@forinda/kickjs'
import { HelloService } from './hello.service'

// `Ctx<KickRoutes.HelloController['<method>']>` is generated by
// `kick typegen` (auto-run on `kick dev`). The first run after a fresh
// scaffold creates `.kickjs/types/routes.ts` so this file typechecks.
// See https://forinda.github.io/kick-js/guide/typegen.

@Controller()
export class HelloController {
  @Autowired() private readonly helloService!: HelloService

  @Get('/')
  index(ctx: Ctx<KickRoutes.HelloController['index']>) {
    ctx.json(this.helloService.greet('World'))
  }

  @Get('/health')
  health(ctx: Ctx<KickRoutes.HelloController['health']>) {
    ctx.json(this.helloService.healthCheck())
  }
}
