import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from 'node:fs'
import { join, relative, dirname } from 'node:path'

/** Regex to find decorator + class name combinations */
const CLASS_PATTERNS = [
  /@Service\s*\([^)]*\)\s*(?:export\s+)?class\s+(\w+)/g,
  /@Controller\s*\([^)]*\)\s*(?:export\s+)?class\s+(\w+)/g,
  /@Repository\s*\([^)]*\)\s*(?:export\s+)?class\s+(\w+)/g,
  /@Injectable\s*\([^)]*\)\s*(?:export\s+)?class\s+(\w+)/g,
  /@Component\s*\([^)]*\)\s*(?:export\s+)?class\s+(\w+)/g,
]

interface DiscoveredClass {
  name: string
  kind: string
  filePath: string
}

/** Recursively scan a directory for TypeScript files */
function scanDir(dir: string, files: string[] = []): string[] {
  if (!existsSync(dir)) return files
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      if (entry === 'node_modules' || entry === 'dist') continue
      scanDir(full, files)
    } else if (entry.endsWith('.ts') && !entry.endsWith('.d.ts') && !entry.endsWith('.test.ts')) {
      files.push(full)
    }
  }
  return files
}

/** Scan source files for decorated classes */
export function discoverClasses(srcDir: string): DiscoveredClass[] {
  const files = scanDir(srcDir)
  const classes: DiscoveredClass[] = []

  for (const filePath of files) {
    const code = readFileSync(filePath, 'utf-8')

    // Quick check — skip files without KickJS imports
    if (!code.includes('@forinda/kickjs') && !code.includes('@forinda/kickjs-core')) continue

    for (const pattern of CLASS_PATTERNS) {
      // Reset regex lastIndex for each file
      pattern.lastIndex = 0
      let match
      while ((match = pattern.exec(code)) !== null) {
        const kind = pattern.source.includes('Service')
          ? 'service'
          : pattern.source.includes('Controller')
            ? 'controller'
            : pattern.source.includes('Repository')
              ? 'repository'
              : pattern.source.includes('Injectable')
                ? 'injectable'
                : 'component'
        classes.push({
          name: match[1],
          kind,
          filePath,
        })
      }
    }
  }

  return classes
}

/**
 * Generate a `.kickjs/types/container.d.ts` file with a fully typed ContainerTokenMap.
 *
 * This enables `container.resolve('UserService')` to return `UserService` (not `any`).
 *
 * @param rootDir — project root directory
 * @param srcDir — source directory to scan (default: 'src')
 */
export function generateContainerTypes(rootDir: string, srcDir: string = 'src'): string {
  const fullSrcDir = join(rootDir, srcDir)
  const outDir = join(rootDir, '.kickjs', 'types')
  const outFile = join(outDir, 'container.d.ts')

  const classes = discoverClasses(fullSrcDir)

  if (classes.length === 0) {
    const content = [
      '// Auto-generated by @forinda/kickjs-vite typegen',
      '// No decorated classes found',
      'export {}',
      '',
    ].join('\n')
    mkdirSync(outDir, { recursive: true })
    writeFileSync(outFile, content)
    return outFile
  }

  const imports: string[] = []
  const entries: string[] = []

  for (const cls of classes) {
    const relPath = relative(outDir, cls.filePath).replace(/\.ts$/, '').replace(/\\/g, '/') // Windows compat
    imports.push(`import type { ${cls.name} } from '${relPath}';`)
    entries.push(`    '${cls.name}': ${cls.name};`)
  }

  const content = [
    '// Auto-generated by @forinda/kickjs-vite typegen',
    '// Do not edit manually — regenerated on `kick typegen` or during dev',
    '',
    ...imports,
    '',
    'declare module "@forinda/kickjs-core" {',
    '  interface ContainerTokenMap {',
    ...entries,
    '  }',
    '',
    '  interface Container {',
    '    resolve<K extends keyof ContainerTokenMap>(token: K): ContainerTokenMap[K];',
    '  }',
    '}',
    '',
  ].join('\n')

  mkdirSync(outDir, { recursive: true })
  writeFileSync(outFile, content)
  return outFile
}
