/**
 * Virtual module plugin for KickJS — generates the `virtual:kickjs/app`
 * module that bridges Vite and the KickJS application.
 *
 * Virtual modules are Vite's mechanism for generating code at build/serve
 * time that doesn't exist on disk. When the dev server calls
 * `ssrLoadModule('virtual:kickjs/app')`, this plugin generates the code
 * that imports and re-exports the user's application entry.
 *
 * In the future, this will also support auto-discovery of `@Module` classes
 * (Step 4 in v3/plan.md) and container manifest generation.
 *
 * @see https://vite.dev/guide/api-plugin.html#virtual-modules-convention
 *
 * @module @forinda/kickjs-vite/virtual-modules
 */

import type { Plugin } from 'vite'
import type { PluginContext } from './types'

/** Prefix for resolved virtual module IDs (Vite convention) */
const VIRTUAL_PREFIX = '\0'

/** Virtual module ID for the KickJS application entry */
const VIRTUAL_APP = 'virtual:kickjs/app'

/** Resolved virtual module ID (with \0 prefix to mark as virtual) */
const RESOLVED_APP = `${VIRTUAL_PREFIX}${VIRTUAL_APP}`

/**
 * Creates the virtual modules plugin.
 *
 * Currently provides one virtual module:
 * - `virtual:kickjs/app` — re-exports the user's application entry
 *
 * The dev server plugin imports this on every request via `ssrLoadModule()`.
 * When any source file changes, Vite invalidates the module graph and the
 * next import returns fresh code — this is how server-side HMR works.
 *
 * Future virtual modules (planned for Steps 4-5):
 * - `virtual:kickjs/modules` — auto-discovered `@Module` classes
 * - `virtual:kickjs/manifest` — container metadata for DevTools
 *
 * @param ctx - Shared plugin context (entry file, root directory)
 * @returns Vite plugin
 */
export function kickjsVirtualModulesPlugin(ctx: PluginContext): Plugin {
  return {
    name: 'kickjs:virtual-modules',

    /**
     * Resolve virtual module IDs.
     * Tells Vite that `virtual:kickjs/app` is a valid module ID
     * and maps it to our internal resolved ID.
     */
    resolveId(id: string) {
      if (id === VIRTUAL_APP) {
        return RESOLVED_APP
      }
    },

    /**
     * Load virtual module content.
     * Generates the code for `virtual:kickjs/app` that imports the user's
     * entry file and re-exports the Express app.
     *
     * The generated code:
     * 1. Imports the user's entry file (which calls `bootstrap()`)
     * 2. Re-exports everything from it (including the `app` export)
     *
     * The dev server plugin then does:
     *   `const { app } = await ssrLoadModule('virtual:kickjs/app')`
     * and uses `app.handle(req, res, next)` to route requests through Express.
     */
    load(id: string) {
      if (id !== RESOLVED_APP) return

      // Generate code that imports and re-exports the user's entry
      // The entry file should: export const app = bootstrap({ modules: [...] })
      return [
        `// Auto-generated by @forinda/kickjs-vite`,
        `// Imports the user's application entry and re-exports the Express app.`,
        `// Vite's module graph tracks this — file changes trigger re-evaluation.`,
        `export * from '${ctx.entry}'`,
      ].join('\n')
    },
  }
}

export { VIRTUAL_APP, RESOLVED_APP }
