import type { Plugin } from 'vite'
import type { PluginContext } from './context'

const VIRTUAL_PREFIX = 'virtual:kickjs/'
const RESOLVED_PREFIX = '\0virtual:kickjs/'

/** Virtual module IDs used by the KickJS Vite plugin */
export const virtualIds = {
  serverEntry: `${VIRTUAL_PREFIX}server-entry`,
  appModules: `${VIRTUAL_PREFIX}app-modules`,
} as const

/**
 * Virtual modules plugin — generates code dynamically based on discovered modules.
 *
 * - `virtual:kickjs/server-entry` — imports and re-exports the user's entry file
 * - `virtual:kickjs/app-modules` — aggregates all discovered @Controller/@Service modules
 */
export function kickjsVirtualModules(ctx: PluginContext): Plugin {
  return {
    name: 'kickjs:virtual-modules',
    enforce: 'pre',

    resolveId(id) {
      if (id.startsWith(VIRTUAL_PREFIX)) {
        return '\0' + id
      }
    },

    load(id) {
      if (id === RESOLVED_PREFIX + 'server-entry') {
        return `export * from "/${ctx.entry}";`
      }

      if (id === RESOLVED_PREFIX + 'app-modules') {
        // Generate imports for all discovered decorated modules
        const imports: string[] = []
        const names: string[] = []
        let i = 0
        for (const [filePath, kinds] of ctx.discoveredModules) {
          if (kinds.has('controller') || kinds.has('service') || kinds.has('repository')) {
            const varName = `mod${i++}`
            imports.push(`import * as ${varName} from "/${filePath}";`)
            names.push(varName)
          }
        }
        return [
          '// Auto-generated by @forinda/kickjs-vite',
          ...imports,
          `export const modules = [${names.join(', ')}];`,
          `export const moduleCount = ${names.length};`,
        ].join('\n')
      }
    },
  }
}

/** Invalidate all virtual modules in the Vite module graph */
export function invalidateVirtualModules(ctx: PluginContext): void {
  if (!ctx.server) return
  for (const id of Object.values(virtualIds)) {
    const mod = ctx.server.moduleGraph.getModuleById('\0' + id)
    if (mod) {
      ctx.server.moduleGraph.invalidateModule(mod)
    }
  }
}
