import type { ColumnSnapshot, FkAction } from '../../snapshot/types'

/**
 * Runtime + type representation of a column reference (e.g. `users.id`).
 * Carries the parent table name, the column's own name, plus runtime
 * accessors used by FK thunks and constraint builders.
 *
 * Exported so adopters can annotate self-referencing thunks without
 * spelling the shape inline:
 *
 *   parentId: uuid().references((): ColumnRef => categories.id)
 *
 * Without the annotation the initializer of a self-referencing const
 * trips TS7022 — TS needs to infer the const while the initializer
 * already references it.
 */
export interface ColumnRef {
  __tableName: string
  __name: string
  __builder: ColumnBuilder
  __state: () => ReturnType<ColumnBuilder['__state']>
}

/**
 * Resolved FK spec — `table` / `column` are pulled by invoking `thunk()`
 * lazily. The thunk pattern lets self-referencing tables work:
 *
 *   const categories = table('categories', {
 *     id: uuid().primaryKey().defaultRandom(),
 *     parentId: uuid().references((): ColumnRef => categories.id),
 *   })
 *
 * If we resolved at `.references()` call time, `categories` would TDZ-fail
 * inside its own initializer. Storing the thunk and resolving on read
 * (extract / render / emit) defers until after the const binding lands.
 */
/**
 * A column ref that knows its column's value type — what lets a foreign key
 * be checked against the column it points at (`fk()`). Assignable to
 * `ColumnRef`, so every existing ref-taking API keeps working.
 */
export type TypedColumnRef<T> = ColumnRef & { readonly __valueType?: T }

/** Typed refs for a column record — one per column. */
export type TypedColumnRefs<C> = {
  [K in keyof C]: TypedColumnRef<C[K] extends ColumnBuilder<infer T> ? T : never>
}

export interface FkSpec {
  thunk: () => ColumnRef
  onDelete: FkAction
  onUpdate: FkAction
  /**
   * The constraint's name in the database.
   *
   * Omitted for schemas written by hand — the name is then derived as
   * `<table>_<column>_fk`. It is set when the schema was generated by
   * `kick db introspect`, because a database names its constraints itself:
   * Postgres' own default is `<table>_<column>_fkey`, and a DBA may have
   * chosen anything. Dropping the real name would make the next diff want to
   * rename every foreign key in the schema.
   */
  name?: string
}

export interface ColumnState {
  type: string
  nullable: boolean
  default: string | null
  primaryKey: boolean
  unique: boolean
  references: FkSpec | null
  /**
   * A column kick/db maintains itself: `'updatedAt'` (set on every update),
   * `'version'` (incremented on every update), `'softDelete'` (rows with it
   * set are skipped by relational reads). Never part of the snapshot — it
   * changes queries, not the schema.
   */
  managed?: 'updatedAt' | 'version' | 'softDelete'
  generated?: { expression: string; stored: boolean }
  identity?: 'always' | 'byDefault'
  /** `$defaultFn`: computed in JS for each inserted row that doesn't set it. */
  defaultFn?: () => unknown
  /** `$onUpdate`: computed in JS for each update that doesn't set it. */
  onUpdateFn?: () => unknown
}

/**
 * Type-only brand attached to a column when it's auto-assigned by the
 * database (serial / bigserial / smallserial), has a runtime default
 * (`.default(...)`), or carries an expression default
 * (`uuid().defaultRandom()`, `timestamp().defaultNow()`). `SchemaToTypes<S>`
 * reads this marker and wraps the column type in Kysely's `Generated<T>` so
 * adopters can omit the column on insert.
 *
 * Runtime is a no-op — the symbol never reaches a value.
 */
export const KICK_GENERATED = Symbol.for('@forinda/kickjs-db/Generated')
export type GeneratedBrand = { readonly [KICK_GENERATED]?: true }

/**
 * Type-only brand for a column the database always computes — a generated
 * column, or an identity `GENERATED ALWAYS`. `SchemaToTypes<S>` wraps it in
 * Kysely's `GeneratedAlways<T>`, so it can't be inserted or updated.
 */
export const KICK_GENERATED_ALWAYS = Symbol.for('@forinda/kickjs-db/GeneratedAlways')
export type GeneratedAlwaysBrand = { readonly [KICK_GENERATED_ALWAYS]?: true }

/**
 * Type-only brand attached to a column when `.notNull()` or `.primaryKey()`
 * is called. `SchemaToTypes<S>` reads this brand to decide whether the
 * column type is `T` (NOT NULL) or `T | null` (default nullable).
 *
 * Why a brand instead of a class generic: chained methods (notNull,
 * primaryKey) can return `this & NotNullBrand` to narrow nullability while
 * preserving the subclass identity — so `uuid().primaryKey().defaultRandom()`
 * still resolves `defaultRandom()` on `UuidBuilder`. A class generic
 * `<TNullable>` would collapse the subclass back to the parent.
 */
export const KICK_NOT_NULL = Symbol.for('@forinda/kickjs-db/NotNull')
export type NotNullBrand = { readonly [KICK_NOT_NULL]?: true }

/**
 * Re-attach the nullability / generated brands after a transform that
 * must return a *new* builder type (e.g. `.array()` widening `T` to
 * `T[]`). Without this, `integer().notNull().array()` silently dropped
 * `NotNullBrand` and the row type regressed to `number[] | null`.
 *
 * Uses the same `extends` checks as `SchemaToTypes` (client/schema-types.ts)
 * so detection stays consistent in both directions.
 */
export type PreserveBrands<Self, Out> = Out &
  (Self extends NotNullBrand ? NotNullBrand : unknown) &
  (Self extends GeneratedBrand ? GeneratedBrand : unknown) &
  (Self extends GeneratedAlwaysBrand ? GeneratedAlwaysBrand : unknown)

/**
 * Phantom-typed column builder. The `T` generic carries the column's TS
 * value type (number / string / Date / etc.); nullability is tracked via
 * the `NotNullBrand` intersection rather than a class generic so chain
 * methods preserve subclass identity.
 *
 * Both `T` and the brand are erased at runtime; they exist purely so
 * `SchemaToTypes<S>` can pull them out per column.
 */
export class ColumnBuilder<T = unknown> {
  // Phantom param shows up in the public surface so the type system sees
  // it. Reading it at runtime is intentionally not supported.
  declare readonly __t?: T

  protected state: ColumnState

  constructor(type: string, defaults: Partial<ColumnState> = {}) {
    this.state = {
      type,
      nullable: defaults.nullable ?? true,
      default: defaults.default ?? null,
      primaryKey: defaults.primaryKey ?? false,
      unique: defaults.unique ?? false,
      references: defaults.references ?? null,
    }
  }

  notNull(): this & NotNullBrand {
    this.state.nullable = false
    return this as this & NotNullBrand
  }

  primaryKey(): this & NotNullBrand {
    this.state.primaryKey = true
    this.state.nullable = false
    return this as this & NotNullBrand
  }

  unique(): this {
    this.state.unique = true
    return this
  }

  array(): PreserveBrands<this, ColumnBuilder<T[]>> {
    this.state.type = `${this.state.type}[]`
    return this as unknown as PreserveBrands<this, ColumnBuilder<T[]>>
  }

  references(
    target: () => ColumnRef,
    opts: { onDelete?: FkAction; onUpdate?: FkAction; name?: string } = {},
  ): this {
    // Store the thunk — do NOT invoke it here. Self-referencing tables
    // pass `() => self.id` whose binding does not exist yet.
    this.state.references = {
      thunk: target,
      onDelete: opts.onDelete ?? 'no_action',
      onUpdate: opts.onUpdate ?? 'no_action',
      // Only carried when given: an absent name means "derive it", and
      // storing the derived value here would make it indistinguishable from
      // an explicit one that happens to match.
      ...(opts.name === undefined ? {} : { name: opts.name }),
    }
    return this
  }

  /**
   * Mark the column as having a runtime / DB-assigned default. The
   * `GeneratedBrand` flows into `SchemaToTypes<S>` so the column wraps
   * in `Generated<T>` — adopters can `INSERT` without specifying it.
   *
   * Accepts the natural literal for the column type — `boolean().default(false)`,
   * `integer().default(0)`, `varchar().default('active')`. Non-string
   * literals are normalised to their SQL-literal text so the snapshot
   * (`ColumnSnapshot.default: string | null`) and migration emitter stay
   * string-only. For a quoted string default the text is the value
   * itself (`'active'`); booleans/numbers emit bare (`false`, `0`).
   */
  default(value: string | number | boolean): this & GeneratedBrand {
    this.state.default = typeof value === 'string' ? value : String(value)
    return this as this & GeneratedBrand
  }

  /**
   * A default computed in JS for each inserted row that doesn't set this
   * column — an id generator, a slug, a value from config:
   * `id: text().primaryKey().$defaultFn(() => ulid())`. Not part of the
   * schema: the database has no default, so raw SQL inserts must set it.
   */
  $defaultFn(fn: () => T): this & GeneratedBrand {
    this.state.defaultFn = fn
    return this as this & GeneratedBrand
  }

  /**
   * A value computed in JS for each update (and an upsert's update branch)
   * that doesn't set this column: `revisedBy: text().$onUpdate(() => currentUser())`.
   * Like `onUpdateNow()`, with your own value. Inserts don't call it.
   */
  $onUpdate(fn: () => T): this {
    this.state.onUpdateFn = fn
    return this
  }

  /**
   * Set this column to the current time on every update that doesn't set it
   * itself — `updatedAt: timestamp().notNull().defaultNow().onUpdateNow()`.
   */
  onUpdateNow(): this {
    this.state.managed = 'updatedAt'
    return this
  }

  /**
   * Mark this column — a nullable timestamp — as the soft-delete marker:
   * relational reads (`db.query`) skip rows where it's set, at every level,
   * unless asked `withDeleted: true`. Soft-delete by setting it.
   */
  softDelete(): this {
    this.state.managed = 'softDelete'
    return this
  }

  /**
   * Computed by the database from other columns, on every write:
   * `total: numeric(12, 2).generatedAlwaysAs('price * quantity')`. The SQL is
   * passed through as written. Stored by default; `{ stored: false }` makes
   * it virtual, computed on read (MySQL, SQLite, Postgres 18+). It can't be
   * inserted or updated.
   */
  generatedAlwaysAs(
    expression: string,
    options: { stored?: boolean } = {},
  ): this & GeneratedAlwaysBrand {
    this.state.generated = { expression, stored: options.stored ?? true }
    return this as this & GeneratedAlwaysBrand
  }

  /**
   * An identity column the database numbers and won't let you set (Postgres)
   * — the SQL-standard successor to `serial`.
   */
  generatedAlwaysAsIdentity(): this & NotNullBrand & GeneratedAlwaysBrand {
    this.state.identity = 'always'
    this.state.nullable = false
    return this as this & NotNullBrand & GeneratedAlwaysBrand
  }

  /** An identity column the database numbers unless a value is given (Postgres). */
  generatedByDefaultAsIdentity(): this & NotNullBrand & GeneratedBrand {
    this.state.identity = 'byDefault'
    this.state.nullable = false
    return this as this & NotNullBrand & GeneratedBrand
  }

  /** The role kick/db maintains this column in, if any. */
  managedAs(): ColumnState['managed'] {
    return this.state.managed
  }

  toJSON(name: string): ColumnSnapshot {
    return {
      name,
      type: this.state.type,
      nullable: this.state.nullable,
      default: this.state.default,
      primaryKey: this.state.primaryKey,
      // Only when set, so other columns serialize as they always have.
      ...(this.state.generated ? { generated: { ...this.state.generated } } : {}),
      ...(this.state.identity ? { identity: this.state.identity } : {}),
    }
  }

  // Internal accessor for table()/diff to read full state including unique/references.
  __state(): Readonly<ColumnState> {
    return this.state
  }
}
