/**
 * Walks every `assetMap` entry's source directory + emits a typed
 * `KickAssets` ambient augmentation (assets-plan.md PR 4). Generates
 * `.kickjs/types/assets.d.ts` so adopters get autocomplete on
 * `assets.<namespace>.<key>` and `@Asset('<namespace>/<key>')`.
 *
 * Pure module — no side effects beyond what the caller does with the
 * returned content. Mirrors the shape of `renderPlugins` /
 * `renderRegistry` in the generator so the typegen output stays
 * consistent across surfaces.
 *
 * @module @forinda/kickjs-cli/typegen/asset-types
 */

import { readdirSync, statSync } from 'node:fs'
import { extname, resolve, sep } from 'node:path'
import type { AssetMapEntry } from '../config'

export interface DiscoveredAssetEntry {
  namespace: string
  key: string
}

export interface DiscoveredAssets {
  entries: DiscoveredAssetEntry[]
  count: number
}

export function discoverAssets(
  assetMap: Record<string, AssetMapEntry> | undefined,
  cwd: string,
): DiscoveredAssets {
  if (!assetMap) return { entries: [], count: 0 }

  const seen = new Map<string, DiscoveredAssetEntry>()
  for (const [namespace, entry] of Object.entries(assetMap)) {
    if (!entry || typeof entry.src !== 'string') continue
    const srcAbs = resolve(cwd, entry.src)
    if (!isDir(srcAbs)) continue
    const matches = walk(srcAbs, srcAbs).filter((rel) =>
      entry.glob ? matchesLite(rel, entry.glob) : true,
    )
    matches.sort()
    for (const rel of matches) {
      const key = stripExt(rel)
      const logical = `${namespace}/${key}`
      seen.set(logical, { namespace, key })
    }
  }
  return { entries: [...seen.values()], count: seen.size }
}

export function renderAssetTypes(discovered: DiscoveredAssets): string {
  const HEADER = `/* eslint-disable */
// AUTO-GENERATED by \`kick typegen\`. DO NOT EDIT.
// Re-run with \`kick typegen\` or rely on \`kick dev\` to refresh.
`

  if (discovered.entries.length === 0) {
    return `${HEADER}
declare module '@forinda/kickjs' {
  /**
   * Map of every typed asset discovered in the project's assetMap.
   * (No assetMap entries discovered yet — declare with
   *  \`assetMap: { name: { src: 'src/...' } }\` in kick.config.ts.)
   */
  interface KickAssets {}
}

export {}
`
  }

  const tree: TreeNode = {}
  for (const entry of discovered.entries) {
    const path = `${entry.namespace}/${entry.key}`.split('/')
    let node = tree
    for (let i = 0; i < path.length - 1; i++) {
      const part = path[i]
      const existing = node[part]
      if (existing === LEAF) {
        // The intermediate path was previously claimed by a leaf —
        // collision between a file (`mails/welcome.ejs`) and a
        // directory (`mails/welcome/x.ejs`). Promote to a sub-tree
        // so the directory wins (consistent with the file-tree
        // semantics; the build pipeline emits a runtime warning for
        // the colliding leaf).
        const promoted: TreeNode = {}
        node[part] = promoted
        node = promoted
      } else {
        if (!existing) node[part] = {}
        node = node[part] as TreeNode
      }
    }
    const leaf = path[path.length - 1]
    if (typeof node[leaf] === 'object') {
      // The leaf collides with an already-built subtree. Skip; the
      // directory wins (matches the promote-to-subtree branch above).
      continue
    }
    node[leaf] = LEAF
  }

  const body = renderTree(tree, '    ')
  return `${HEADER}
declare module '@forinda/kickjs' {
  /**
   * Map of every typed asset discovered in the project's assetMap.
   * Each leaf is a \`() => string\` thunk that returns the resolved
   * absolute path for the file in the current run mode (dev → src,
   * prod → dist).
   */
  interface KickAssets {
${body}
  }
}

export {}
`
}

const LEAF = Symbol('asset-leaf')
type TreeNode = { [key: string]: TreeNode | typeof LEAF }

function renderTree(node: TreeNode, indent: string): string {
  const keys = Object.keys(node).sort()
  const lines: string[] = []
  for (const key of keys) {
    const child = node[key]
    const safeKey = isIdentifier(key) ? key : JSON.stringify(key)
    if (child === LEAF) {
      lines.push(`${indent}${safeKey}: () => string`)
    } else {
      lines.push(`${indent}${safeKey}: {`)
      lines.push(renderTree(child, `${indent}  `))
      lines.push(`${indent}}`)
    }
  }
  return lines.join('\n')
}

function isIdentifier(str: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(str)
}

function isDir(path: string): boolean {
  try {
    return statSync(path).isDirectory()
  } catch {
    return false
  }
}

function walk(root: string, dir: string): string[] {
  let entries
  try {
    entries = readdirSync(dir, { withFileTypes: true })
  } catch {
    return []
  }
  const out: string[] = []
  for (const entry of entries) {
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue
    const full = `${dir}${sep}${entry.name}`
    if (entry.isDirectory()) {
      out.push(...walk(root, full))
    } else if (entry.isFile()) {
      const rel = full
        .slice(root.length + 1)
        .split(sep)
        .join('/')
      out.push(rel)
    }
  }
  return out
}

function stripExt(path: string): string {
  const ext = extname(path)
  return ext ? path.slice(0, -ext.length) : path
}

function matchesLite(relPath: string, pattern: string): boolean {
  if (pattern === '**/*' || pattern === '**') return true
  const singleExt = /^\*\*\/\*\.(\w+)$/.exec(pattern)
  if (singleExt) return relPath.endsWith(`.${singleExt[1]}`)
  const braceExt = /^\*\*\/\*\.\{([^}]+)\}$/.exec(pattern)
  if (braceExt) {
    const exts = braceExt[1].split(',').map((e) => e.trim())
    return exts.some((ext) => relPath.endsWith(`.${ext}`))
  }
  return true
}
