/**
 * Generates `.d.ts` files inside `.kickjs/types/` from the discovered
 * decorated classes and DI tokens. Pattern modeled on React Router's
 * `.react-router/types/` directory.
 *
 * Outputs:
 * - `.kickjs/types/registry.d.ts` — module augmentation for `KickJsRegistry`
 *    that gives `container.resolve('UserService')` the right return type.
 * - `.kickjs/types/services.d.ts` — string-literal union of all known
 *   service-style tokens for tooling autocomplete.
 * - `.kickjs/types/modules.d.ts` — string-literal union of discovered
 *   module class names.
 * - `.kickjs/types/index.d.ts` — re-exports the above (single import target).
 * - `.kickjs/.gitignore` — gitignores the whole folder so generated files
 *   never get committed.
 *
 * ## Collision behaviour
 *
 * If `findCollisions()` returns any duplicate class names:
 * - **Default (`allowDuplicates: false`)** — `generateTypes` throws a
 *   `TokenCollisionError` with a clear message listing every conflicting
 *   file. The caller (CLI) prints it and exits non-zero. Nothing is
 *   written to disk.
 * - **`allowDuplicates: true`** — colliding classes are auto-namespaced
 *   by their relative file path so the registry keys become e.g.
 *   `'modules/users/UserService'` instead of `'UserService'`. Non-colliding
 *   classes still get bare `'ClassName'` keys (smart default).
 *
 * @module @forinda/kickjs-cli/typegen/generator
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join, relative, sep } from 'node:path'
import type {
  ClassCollision,
  DiscoveredAugmentation,
  DiscoveredClass,
  DiscoveredEnv,
  DiscoveredInject,
  DiscoveredPluginOrAdapter,
  DiscoveredRoute,
  DiscoveredToken,
} from './scanner'
import { renderAssetTypes, type DiscoveredAssets } from './asset-types'

/** Header written to every generated file */
const HEADER = `/* eslint-disable */
// AUTO-GENERATED by \`kick typegen\`. DO NOT EDIT.
// Re-run with \`kick typegen\` or rely on \`kick dev\` to refresh.
`

/** Decorators whose classes participate in the DI registry augmentation */
const REGISTRY_DECORATORS = new Set(['Service', 'Repository', 'Injectable', 'Component'])

/** Thrown by `generateTypes` when collisions are found and not allowed */
export class TokenCollisionError extends Error {
  readonly collisions: ClassCollision[]
  constructor(collisions: ClassCollision[]) {
    super(formatCollisionMessage(collisions))
    this.name = 'TokenCollisionError'
    this.collisions = collisions
  }
}

/** Build a human-readable message describing every collision */
function formatCollisionMessage(collisions: ClassCollision[]): string {
  const lines: string[] = ['kick typegen: token collision detected']
  for (const c of collisions) {
    lines.push('')
    lines.push(`  ${c.classes.length} classes named '${c.className}':`)
    for (const cls of c.classes) {
      lines.push(`    - ${cls.relativePath}`)
    }
  }
  lines.push('')
  lines.push('Resolutions:')
  lines.push('  (a) Rename one of the classes')
  lines.push(
    "  (b) Use createToken<T>('namespaced/Name') and import the token explicitly — see @forinda/kickjs",
  )
  lines.push('  (c) Pass --allow-duplicates to namespace the registry keys automatically')
  lines.push("      (e.g. 'modules/users/UserService' instead of 'UserService')")
  return lines.join('\n')
}

/** Compute the module specifier (without extension) used inside `import('...')` */
function importSpecifierFor(targetFile: string, fromFile: string): string {
  const fromDir = dirname(fromFile)
  let rel = relative(fromDir, targetFile).split(sep).join('/')
  rel = rel.replace(/\.(ts|tsx|mts|cts)$/i, '')
  if (!rel.startsWith('.')) rel = './' + rel
  return rel
}

/**
 * Build the namespaced registry key for a colliding class.
 * Strips the `src/` prefix and the file extension, then appends the
 * class name. Example: `src/modules/users/user.service.ts` + `UserService`
 * → `modules/users/UserService`.
 */
function namespacedKeyFor(cls: DiscoveredClass): string {
  const rel = cls.relativePath.replace(/^src\//, '').replace(/\.(ts|tsx|mts|cts)$/i, '')
  // Drop the trailing filename if it's just the class in kebab/snake form —
  // keep the directory path as the namespace.
  const parts = rel.split('/')
  parts.pop()
  const ns = parts.join('/')
  return ns ? `${ns}/${cls.className}` : cls.className
}

/**
 * Render the `KickJsRegistry` module augmentation. Each entry maps a
 * string token to the imported class type.
 *
 * Default-exported classes are imported as `import('...').default`.
 *
 * `collidingNames` lists class names that should be auto-namespaced;
 * everything else gets a bare key.
 */
function renderRegistry(
  classes: DiscoveredClass[],
  outFile: string,
  collidingNames: Set<string>,
): string {
  const seen = new Set<string>()
  const entries: string[] = []

  for (const c of classes) {
    if (!REGISTRY_DECORATORS.has(c.decorator)) continue

    const key = collidingNames.has(c.className) ? namespacedKeyFor(c) : c.className
    if (seen.has(key)) continue
    seen.add(key)

    const spec = importSpecifierFor(c.filePath, outFile)
    const ref = c.isDefault ? `import('${spec}').default` : `import('${spec}').${c.className}`
    entries.push(`    '${key}': ${ref}`)
  }

  const body = entries.length
    ? entries.join('\n')
    : '    // (no services discovered yet — run `kick g service <name>` to add one)'

  return `${HEADER}
declare module '@forinda/kickjs' {
  interface KickJsRegistry {
${body}
  }
}

export {}
`
}

/** Render a string-literal union type containing the given names */
function renderUnion(typeName: string, names: string[], emptyComment: string): string {
  if (names.length === 0) {
    return `${HEADER}
// ${emptyComment}
export type ${typeName} = never
`
  }
  const sorted = [...new Set(names)].toSorted()
  return `${HEADER}
export type ${typeName} =
${sorted.map((n) => `  | '${n}'`).join('\n')}
`
}

/** Render the barrel index that re-exports the union types */
function renderIndex(includeEnv: boolean): string {
  // The kick/routes + kick/env TypegenPlugins write their output to
  // `kick__routes.ts` / `kick__env.ts` (see typegen runner + builtin
  // plugins). The index re-exports them via side-effect imports so
  // `tsconfig include` of `.kickjs/types/` is enough to wire up the
  // augmentations — same surface adopters had before the carve.
  const envImport = includeEnv ? "import './kick__env'\n" : ''
  return `${HEADER}
export type { ServiceToken } from './services'
export type { ModuleToken } from './modules'

// The registry, routes, plugins, assets, and env augmentations are
// loaded as side-effects — importing this file (or having it on
// tsconfig include) is enough for \`container.resolve()\`,
// \`Ctx<KickRoutes.UserController['getUser']>\`,
// \`dependsOn: ['TenantAdapter']\`, \`assets.mails.welcome()\`, and
// \`@Value('PORT')\` to resolve.
import './registry'
import './kick__routes'
import './plugins'
import './augmentations'
import './assets'
${envImport}`
}

/**
 * Render the `KickJsPluginRegistry` augmentation. Each entry maps the
 * literal `name` field of a plugin/adapter to a marker type (the
 * registry value isn't load-bearing at runtime — `dependsOn` only cares
 * about `keyof`, so any non-`never` type works). We emit `'plugin'` /
 * `'adapter'` strings so DevTools can later read the registry to tell
 * the kinds apart without a second source of truth.
 *
 * When the project has no discoverable plugins/adapters, the augmentation
 * is intentionally empty rather than skipped so the `keyof` constraint
 * resolves to `never` (which is harmless — `dependsOn: []` still works).
 */
function renderPlugins(items: DiscoveredPluginOrAdapter[]): string {
  // Dedupe by name — two declarations with the same name are a runtime
  // boot-time error in `mount-sort.ts`; we surface the conflict via a
  // single registry entry rather than a duplicate-key TS error.
  const byName = new Map<string, DiscoveredPluginOrAdapter>()
  for (const item of items) {
    if (!byName.has(item.name)) byName.set(item.name, item)
  }

  const sorted = [...byName.values()].toSorted((a, b) => a.name.localeCompare(b.name))
  const entries = sorted.map((item) => `    '${item.name}': '${item.kind}'`).join('\n')

  const body = entries
    ? entries
    : '    // (no plugins/adapters discovered yet — `defineAdapter`/`definePlugin` calls feed this)'

  return `${HEADER}
declare module '@forinda/kickjs' {
  /**
   * Map of every plugin/adapter \`name\` discovered in the project. The
   * value type is the kind tag (\`'plugin'\` or \`'adapter'\`); the
   * \`keyof\` of this interface narrows \`dependsOn\` so misspelled deps
   * become compile errors instead of boot-time \`MissingMountDepError\`.
   */
  interface KickJsPluginRegistry {
${body}
  }
}

export {}
`
}

/**
 * Render the augmentation manifest — one block per `defineAugmentation`
 * call discovered in the project. The output is a `.d.ts` file that
 * does nothing at runtime but acts as in-IDE documentation: adopters
 * jumping into it see every interface their plugins offer for
 * augmentation, alongside any `description` / `example` the plugin
 * authors provided.
 */
function renderAugmentations(items: DiscoveredAugmentation[]): string {
  if (items.length === 0) {
    return `${HEADER}
// No augmentations discovered.
//
// Plugins advertise augmentable interfaces via:
//
//   import { defineAugmentation } from '@forinda/kickjs'
//   defineAugmentation('FeatureFlags', {
//     description: 'Feature flag shape consumed by FlagsPlugin',
//     example: '{ beta: boolean; rolloutPercentage: number }',
//   })
//
// See \`docs/guide/typegen.md#augmentations\` for the full pattern.
export {}
`
  }

  // Dedupe by name — multiple plugins shouldn't claim the same name,
  // but if they do we keep the first.
  const byName = new Map<string, DiscoveredAugmentation>()
  for (const item of items) {
    if (!byName.has(item.name)) byName.set(item.name, item)
  }

  const blocks: string[] = []
  for (const item of [...byName.values()].toSorted((a, b) => a.name.localeCompare(b.name))) {
    const docLines: string[] = []
    if (item.description) {
      // Description may itself be multi-line — preserve line breaks
      // so JSDoc renderers wrap intent correctly.
      for (const line of item.description.split('\n')) docLines.push(` * ${line}`)
    }
    if (item.example) {
      // Split the example so each line is prefixed with ` * ` — without
      // this, raw newlines inside the example string broke the JSDoc
      // comment and IDEs rendered the whole block as one mangled line.
      // This is what made `defineAugmentation({ example: '<huge object>' })`
      // unusable for anything beyond a one-liner.
      docLines.push(` * @example`, ` * \`\`\`ts`)
      for (const line of item.example.split('\n')) docLines.push(` * ${line}`)
      docLines.push(` * \`\`\``)
    }
    docLines.push(` * @see ${item.relativePath}`)
    blocks.push(
      ['/**', ...docLines, ' */', `export interface ${item.name}Augmentation {}`].join('\n'),
    )
  }

  return `${HEADER}
// Catalogue of augmentable interfaces in this project. The interfaces
// below are documentation only — augment the source-of-truth interfaces
// in your own \`d.ts\` files (the framework declares the actual types).

${blocks.join('\n\n')}
`
}

/** Result of a typegen run — useful for logging and tests */
export interface GenerateResult {
  /** Number of registry entries written */
  registryEntries: number
  /** Number of service tokens (classes + createToken + @Inject literals) */
  serviceTokens: number
  /** Number of module tokens written */
  moduleTokens: number
  /** Number of route entries written into KickRoutes */
  routeEntries: number
  /** Number of plugin/adapter names registered into KickJsPluginRegistry */
  pluginEntries: number
  /** Number of `defineAugmentation` calls catalogued */
  augmentationEntries: number
  /** Number of typed asset entries (every file in every assetMap dir) */
  assetEntries: number
  /** Whether a typed env augmentation was emitted */
  envWritten: boolean
  /** Files that were written */
  written: string[]
  /** Number of collisions that were auto-namespaced (only > 0 with allowDuplicates) */
  resolvedCollisions: number
}

/** Options for `generateTypes` */
export interface GenerateOptions {
  /** Discovered classes from the scanner */
  classes: DiscoveredClass[]
  /** Discovered route handlers from the scanner */
  routes?: DiscoveredRoute[]
  /** Discovered `createToken('name')` calls */
  tokens?: DiscoveredToken[]
  /** Discovered `@Inject('literal')` calls */
  injects?: DiscoveredInject[]
  /** Detected duplicate class names from the scanner */
  collisions?: ClassCollision[]
  /** Discovered env schema file (or null if none) */
  env?: DiscoveredEnv | null
  /** Plugins/adapters discovered via `defineAdapter`/`definePlugin`/`implements AppAdapter` */
  pluginsAndAdapters?: DiscoveredPluginOrAdapter[]
  /** `defineAugmentation` calls discovered in the project */
  augmentations?: DiscoveredAugmentation[]
  /** Discovered typed assets from the assetMap walker (PR 4 of asset-manager). */
  assets?: DiscoveredAssets
  /** Output directory (typically `<cwd>/.kickjs/types`) */
  outDir: string
  /**
   * When `true`, colliding class names are auto-namespaced by file path
   * instead of throwing. Default: `false`.
   */
  allowDuplicates?: boolean
  /**
   * Schema validator the project uses. When `'zod'`, the generator
   * emits `z.infer<typeof import('...').schema>` for any route whose
   * decorator declared a body/query/params schema identifier that
   * could be statically resolved. When `false` (or omitted), schemas
   * are ignored and `body`/`query`/`params` keep their `unknown`
   * placeholders.
   *
   * Future: `'joi'`, `'yup'`, `'json-schema'`, custom adapters.
   */
  schemaValidator?: 'zod' | false
}

/** Write all generated `.d.ts` files to `outDir` */
export async function generateTypes(opts: GenerateOptions): Promise<GenerateResult> {
  const {
    classes,
    routes = [],
    tokens = [],
    injects = [],
    collisions = [],
    env = null,
    pluginsAndAdapters = [],
    augmentations = [],
    assets = { entries: [], count: 0 } as DiscoveredAssets,
    outDir,
    allowDuplicates = false,
    schemaValidator: _schemaValidator = false,
  } = opts

  if (collisions.length > 0 && !allowDuplicates) {
    throw new TokenCollisionError(collisions)
  }

  await mkdir(outDir, { recursive: true })

  const registryFile = join(outDir, 'registry.d.ts')
  const servicesFile = join(outDir, 'services.d.ts')
  const modulesFile = join(outDir, 'modules.d.ts')
  // routes.ts + env.ts are now owned by the `kick/routes` and
  // `kick/env` typegen plugins (M2.B-T8 carve). They write
  // `kick__routes.ts` / `kick__env.ts` via the plugin runner. Legacy
  // emissions of those files are gone.
  const pluginsFile = join(outDir, 'plugins.d.ts')
  const augmentationsFile = join(outDir, 'augmentations.d.ts')
  const assetsFile = join(outDir, 'assets.d.ts')
  const indexFile = join(outDir, 'index.d.ts')

  const collidingNames = new Set(collisions.map((c) => c.className))
  const registryContent = renderRegistry(classes, registryFile, collidingNames)

  // ServiceToken union — combines class names, createToken literals, and
  // @Inject literals so tooling autocomplete sees every known token.
  const classTokens = classes
    .filter((c) => REGISTRY_DECORATORS.has(c.decorator))
    .map((c) => (collidingNames.has(c.className) ? namespacedKeyFor(c) : c.className))
  const tokenLiterals = tokens.map((t) => t.name)
  const injectLiterals = injects.map((i) => i.name)
  const allServices = [...classTokens, ...tokenLiterals, ...injectLiterals]

  const modules = classes.filter((c) => c.decorator === 'Module').map((c) => c.className)

  const servicesContent = renderUnion(
    'ServiceToken',
    allServices,
    '(no tokens discovered — declare with createToken<T>() or `kick g service <name>`)',
  )
  const modulesContent = renderUnion(
    'ModuleToken',
    modules,
    '(no @Module classes discovered — `kick g module <name>` to add one)',
  )
  const pluginsContent = renderPlugins(pluginsAndAdapters)
  const augmentationsContent = renderAugmentations(augmentations)
  const assetsContent = renderAssetTypes(assets)
  const indexContent = renderIndex(env !== null)

  await writeFile(registryFile, registryContent, 'utf-8')
  await writeFile(servicesFile, servicesContent, 'utf-8')
  await writeFile(modulesFile, modulesContent, 'utf-8')
  await writeFile(pluginsFile, pluginsContent, 'utf-8')
  await writeFile(augmentationsFile, augmentationsContent, 'utf-8')
  await writeFile(assetsFile, assetsContent, 'utf-8')
  await writeFile(indexFile, indexContent, 'utf-8')

  const written = [
    registryFile,
    servicesFile,
    modulesFile,
    pluginsFile,
    augmentationsFile,
    assetsFile,
    indexFile,
  ]

  // Write `.gitignore` at the .kickjs root (one level up from outDir)
  const kickjsRoot = dirname(outDir)
  await writeFile(join(kickjsRoot, '.gitignore'), '# Auto-generated by kick typegen\n*\n', 'utf-8')

  // Dedupe the plugin/adapter count — two declarations with the same
  // name collapse to one registry entry (mount-sort still throws at
  // boot, but the typegen layer reports the unique surface).
  const uniquePluginNames = new Set(pluginsAndAdapters.map((p) => p.name)).size
  const uniqueAugmentations = new Set(augmentations.map((a) => a.name)).size

  return {
    registryEntries: classTokens.length,
    serviceTokens: new Set(allServices).size,
    moduleTokens: modules.length,
    routeEntries: routes.length,
    pluginEntries: uniquePluginNames,
    augmentationEntries: uniqueAugmentations,
    assetEntries: assets.count,
    envWritten: env !== null,
    written,
    resolvedCollisions: collisions.length,
  }
}
