// Typegen runner — M2.B-T7.
//
// Sequentially invokes each plugin's generate(), prepends a banner, and
// writes the result to `.kickjs/types/<id>.d.ts` only when the content
// changes. `--check` mode skips writing and throws on the first drift —
// CI gate so generated files in git stay in sync with code.
//
// Sequential (not parallel) on purpose: plugins are cheap, ordering keeps
// log output readable, and adopter plugins may share state via the cwd
// filesystem. Parallel can be added later if a profiler flags it.

import path from 'node:path'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { pathToFileURL } from 'node:url'

import type { KickConfig } from '../config'
import { scanProject, type ScanOptions, type ScanResult } from './scanner'
import type { TypegenContext, TypegenPlugin, TypegenPluginResult } from './plugin'

const TYPES_DIR = '.kickjs/types'
const BANNER_PREFIX = '/* AUTO-GENERATED by kick typegen — do not edit. Plugin: '

export interface RunTypegenOptions {
  cwd: string
  config: KickConfig
  plugins: TypegenPlugin[]
  /** When true: do not write; throw on the first plugin whose output differs. */
  check?: boolean
  /**
   * Optional scanner stub for tests. When set, `ctx.getScanResult()`
   * routes here instead of running the real scanner. Production
   * callers leave this undefined.
   */
  scan?: (opts: ScanOptions) => Promise<ScanResult>
}

export async function runTypegen(opts: RunTypegenOptions): Promise<TypegenPluginResult[]> {
  const typesDirAbs = path.resolve(opts.cwd, TYPES_DIR)
  await mkdir(typesDirAbs, { recursive: true })

  // Per-pass memoization of scanProject. Cache keyed by a JSON-stable
  // serialization of the resolved scan options so two plugins asking
  // for the same scan share one walk + extraction. Different option
  // shapes (different srcDir, different envFile) get separate scans.
  const scanCache = new Map<string, Promise<ScanResult>>()
  const scanFn = opts.scan ?? scanProject
  const getScanResult = (scanOpts: ScanOptions): Promise<ScanResult> => {
    const key = JSON.stringify(scanOpts)
    let pending = scanCache.get(key)
    if (!pending) {
      pending = scanFn(scanOpts)
      scanCache.set(key, pending)
    }
    return pending
  }

  const ctx: TypegenContext = {
    cwd: opts.cwd,
    config: opts.config,
    async importTs(abs) {
      return (await import(pathToFileURL(abs).href)) as never
    },
    async writeFile(relPath, contents) {
      const abs = path.resolve(opts.cwd, relPath)
      await mkdir(path.dirname(abs), { recursive: true })
      await writeFile(abs, contents, 'utf8')
    },
    getScanResult,
    log: console,
  }

  const results: TypegenPluginResult[] = []
  for (const plugin of opts.plugins) {
    const out = await plugin.generate(ctx)
    if (out === null) {
      results.push({ id: plugin.id, status: 'skipped' })
      continue
    }

    // Slashes in ids (kick/db) → __ on disk so they're valid filenames.
    // Default extension is .d.ts (declaration only); plugins emitting
    // hoisted top-level imports (kick/routes) override to .ts so the
    // bundler resolver sees them as proper modules.
    const ext = plugin.outExtension ?? '.d.ts'
    const file = path.join(typesDirAbs, `${plugin.id.replace(/\//g, '__')}${ext}`)
    const banner = `${BANNER_PREFIX}${plugin.id} */\n\n`
    const next = banner + out + '\n'

    let prev = ''
    if (existsSync(file)) prev = await readFile(file, 'utf8')

    if (prev === next) {
      results.push({ id: plugin.id, status: 'unchanged', outFile: file })
      continue
    }

    if (opts.check) {
      throw new Error(`kick typegen --check: drift detected for ${plugin.id} (${file})`)
    }
    await writeFile(file, next, 'utf8')
    results.push({ id: plugin.id, status: 'written', outFile: file })
  }

  return results
}
