// Typegen runner — M2.B-T7.
//
// Sequentially invokes each plugin's generate(), prepends a banner, and
// writes the result to `.kickjs/types/<id>.d.ts` only when the content
// changes. `--check` mode skips writing, collects every plugin whose
// output drifted, and throws `TypegenDriftError` listing all of them —
// CI gate so generated files in git stay in sync with code.
//
// Sequential (not parallel) on purpose: plugins are cheap, ordering keeps
// log output readable, and adopter plugins may share state via the cwd
// filesystem. Parallel can be added later if a profiler flags it.

import path from 'node:path'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { pathToFileURL } from 'node:url'

import type { KickConfig } from '../config'
import {
  scanProject,
  scanProjectIncremental,
  type ScanDelta,
  type ScanOptions,
  type ScanResult,
} from './scanner'
import { TypegenDriftError } from './plugin'
import type { TypegenContext, TypegenPlugin, TypegenPluginResult } from './plugin'

const TYPES_DIR = '.kickjs/types'
const BANNER_PREFIX = '/* AUTO-GENERATED by kick typegen — do not edit. Plugin: '

export interface RunTypegenOptions {
  cwd: string
  config: KickConfig
  plugins: TypegenPlugin[]
  /** When true: do not write; throw on the first plugin whose output differs. */
  check?: boolean
  /**
   * Optional scanner stub for tests. When set, `ctx.getScanResult()`
   * routes here instead of running the real scanner. Production
   * callers leave this undefined.
   */
  scan?: (opts: ScanOptions) => Promise<ScanResult>
  /**
   * Exact watcher delta (e.g. from Vite's chokidar). When present, the
   * scan runs incrementally — re-extracting only changed files and
   * skipping the directory walk entirely — instead of a full re-scan.
   * Ignored when a `scan` stub is supplied (tests).
   */
  changedFiles?: ScanDelta
}

export async function runTypegen(opts: RunTypegenOptions): Promise<TypegenPluginResult[]> {
  const typesDirAbs = path.resolve(opts.cwd, TYPES_DIR)
  // `--check` is read-only: it must not touch the working tree at all.
  // Creating the output directory here would leave a clean checkout dirty
  // just by running the gate. Everything the check path does is reads
  // (`existsSync` + `readFile`), which work fine when the dir is absent —
  // a missing directory simply means every plugin drifts, which is the
  // correct verdict for a repo with no generated types committed.
  if (!opts.check) {
    await mkdir(typesDirAbs, { recursive: true })
  }

  // Per-pass memoization of scanProject. Cache keyed by a stable
  // serialization of the resolved scan options so two plugins asking
  // for the same scan share one walk + extraction. Different option
  // shapes (different srcDir, different envFile) get separate scans.
  // We deliberately do NOT use JSON.stringify on the raw options: its
  // output is sensitive to property insertion order, so two plugins
  // that build their options object in different orders would miss
  // the cache and trigger duplicate scans.
  const scanCache = new Map<string, Promise<ScanResult>>()
  const scanFn = opts.scan ?? scanProject
  // Persistent per-file extraction cache lives under `.kickjs/cache`.
  // Injected centrally here so every builtin/plugin scan benefits
  // regardless of how it assembled its ScanOptions. `stableScanKey`
  // ignores `cacheDir`, so the in-pass memo still collapses duplicate
  // scans to a single walk.
  const defaultCacheDir = path.resolve(opts.cwd, '.kickjs', 'cache')
  // Use the incremental scanner only for the real scanner (not a test
  // stub) and only when the caller handed us a precise watcher delta.
  const delta = opts.scan ? undefined : opts.changedFiles
  const getScanResult = (scanOpts: ScanOptions): Promise<ScanResult> => {
    const key = stableScanKey(scanOpts)
    let pending = scanCache.get(key)
    if (!pending) {
      const resolved = { cacheDir: defaultCacheDir, ...scanOpts }
      pending = delta ? scanProjectIncremental(resolved, delta) : scanFn(resolved)
      scanCache.set(key, pending)
    }
    return pending
  }

  const ctx: TypegenContext = {
    cwd: opts.cwd,
    config: opts.config,
    async importTs(abs) {
      return (await import(pathToFileURL(abs).href)) as never
    },
    async writeFile(relPath, contents) {
      const abs = path.resolve(opts.cwd, relPath)
      await mkdir(path.dirname(abs), { recursive: true })
      await writeFile(abs, contents, 'utf8')
    },
    getScanResult,
    log: console,
  }

  const results: TypegenPluginResult[] = []
  const drifted: { id: string; outFile: string }[] = []
  for (const plugin of opts.plugins) {
    // Slashes in ids (kick/db) → __ on disk so they're valid filenames.
    // Default extension is .d.ts (declaration only); plugins emitting
    // hoisted top-level imports (kick/routes) override to .ts so the
    // bundler resolver sees them as proper modules.
    // Computed BEFORE generate() so a failing plugin can still report
    // its `outFile` — the downstream sweep keeps any file in the
    // result set, so a transient generate() throw never deletes this
    // plugin's previously-good output.
    const ext = plugin.outExtension ?? '.d.ts'
    const file = path.join(typesDirAbs, `${plugin.id.replace(/\//g, '__')}${ext}`)

    let out: string | null
    try {
      out = await plugin.generate(ctx)
    } catch (err) {
      // Isolate the failure: one plugin throwing must not abort the
      // rest of the pass (before this guard, a throw in e.g. kick/assets
      // aborted the whole loop, so kick/routes never ran and the sweep
      // then deleted the stale-looking controller route types).
      const msg = err instanceof Error ? err.message : String(err)
      // Under --check there is no "previous output" to keep — we aren't
      // writing. A plugin that can't generate means the gate cannot
      // verify that file, and a gate that can't verify must not pass.
      if (opts.check) {
        throw new Error(`kick typegen --check: ${plugin.id} failed to generate (${msg})`, {
          cause: err,
        })
      }
      ctx.log.error(`  ${plugin.id}: typegen failed (${msg}) — keeping previous output`)
      results.push({ id: plugin.id, status: 'error', outFile: file })
      continue
    }
    if (out === null) {
      results.push({ id: plugin.id, status: 'skipped' })
      continue
    }

    const banner = `${BANNER_PREFIX}${plugin.id} */\n\n`
    const next = banner + out + '\n'

    let prev = ''
    if (existsSync(file)) prev = await readFile(file, 'utf8')

    if (prev === next) {
      results.push({ id: plugin.id, status: 'unchanged', outFile: file })
      continue
    }

    if (opts.check) {
      // Record and keep going — a CI run should report every stale file
      // in one pass, not make the adopter re-run the gate N times to
      // discover them one at a time.
      drifted.push({ id: plugin.id, outFile: file })
      results.push({ id: plugin.id, status: 'drifted', outFile: file })
      continue
    }
    await writeFile(file, next, 'utf8')
    results.push({ id: plugin.id, status: 'written', outFile: file })
  }

  if (drifted.length > 0) throw new TypegenDriftError(drifted)

  return results
}

/**
 * Order-independent cache key for `ScanOptions`. Builds the key from
 * the known fields in a fixed order so semantically equal options
 * always produce the same key regardless of how the caller built the
 * object literal. Arrays (extensions / exclude) are sorted before
 * joining so `['.ts', '.tsx']` and `['.tsx', '.ts']` collide.
 */
function stableScanKey(opts: ScanOptions): string {
  const extensions = (opts.extensions ?? []).slice().toSorted().join(',')
  const exclude = (opts.exclude ?? []).slice().toSorted().join(',')
  return [
    `root=${opts.root}`,
    `cwd=${opts.cwd}`,
    `extensions=${extensions}`,
    `exclude=${exclude}`,
    `envFile=${opts.envFile ?? ''}`,
  ].join('|')
}
