-- REVIEWED: false
ALTER TABLE "workspaces" DROP CONSTRAINT "workspaces_ownerId_fk";
ALTER TABLE "workspace_members" DROP CONSTRAINT "workspace_members_userId_fk";
ALTER TABLE "workspace_members" DROP CONSTRAINT "workspace_members_workspaceId_fk";
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_parentTaskId_fk";
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_reporterId_fk";
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_workspaceId_fk";
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_projectId_fk";
ALTER TABLE "task_labels" DROP CONSTRAINT "task_labels_labelId_fk";
ALTER TABLE "task_labels" DROP CONSTRAINT "task_labels_taskId_fk";
ALTER TABLE "task_assignees" DROP CONSTRAINT "task_assignees_userId_fk";
ALTER TABLE "task_assignees" DROP CONSTRAINT "task_assignees_taskId_fk";
ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_userId_fk";
ALTER TABLE "projects" DROP CONSTRAINT "projects_leadId_fk";
ALTER TABLE "projects" DROP CONSTRAINT "projects_workspaceId_fk";
ALTER TABLE "notifications" DROP CONSTRAINT "notifications_recipientId_fk";
ALTER TABLE "messages" DROP CONSTRAINT "messages_senderId_fk";
ALTER TABLE "messages" DROP CONSTRAINT "messages_channelId_fk";
ALTER TABLE "labels" DROP CONSTRAINT "labels_workspaceId_fk";
ALTER TABLE "comments" DROP CONSTRAINT "comments_authorId_fk";
ALTER TABLE "comments" DROP CONSTRAINT "comments_taskId_fk";
ALTER TABLE "channels" DROP CONSTRAINT "channels_createdById_fk";
ALTER TABLE "channels" DROP CONSTRAINT "channels_projectId_fk";
ALTER TABLE "channels" DROP CONSTRAINT "channels_workspaceId_fk";
ALTER TABLE "channel_members" DROP CONSTRAINT "channel_members_userId_fk";
ALTER TABLE "channel_members" DROP CONSTRAINT "channel_members_channelId_fk";
ALTER TABLE "attachments" DROP CONSTRAINT "attachments_uploaderId_fk";
ALTER TABLE "attachments" DROP CONSTRAINT "attachments_taskId_fk";
ALTER TABLE "activities" DROP CONSTRAINT "activities_actorId_fk";
ALTER TABLE "activities" DROP CONSTRAINT "activities_taskId_fk";
ALTER TABLE "activities" DROP CONSTRAINT "activities_projectId_fk";
ALTER TABLE "activities" DROP CONSTRAINT "activities_workspaceId_fk";
DROP INDEX "workspaces_slug_unique";
DROP INDEX "workspaces_owner_idx";
DROP INDEX "workspace_members_user_idx";
DROP INDEX "workspace_members_workspace_idx";
DROP INDEX "workspace_members_workspace_user_unique";
DROP INDEX "users_email_unique";
DROP INDEX "users_name_idx";
DROP INDEX "tasks_key_unique";
DROP INDEX "tasks_reporter_idx";
DROP INDEX "tasks_parent_idx";
DROP INDEX "tasks_status_idx";
DROP INDEX "tasks_workspace_idx";
DROP INDEX "tasks_project_idx";
DROP INDEX "task_labels_task_label_unique";
DROP INDEX "task_assignees_task_user_unique";
DROP INDEX "refresh_tokens_token_unique";
DROP INDEX "refresh_tokens_user_idx";
DROP INDEX "projects_workspace_idx";
DROP INDEX "projects_workspace_key_unique";
DROP INDEX "notifications_recipient_read_idx";
DROP INDEX "notifications_recipient_idx";
DROP INDEX "messages_sender_idx";
DROP INDEX "messages_channel_idx";
DROP INDEX "labels_workspace_name_unique";
DROP INDEX "comments_author_idx";
DROP INDEX "comments_task_idx";
DROP INDEX "channels_project_idx";
DROP INDEX "channels_workspace_idx";
DROP INDEX "channels_workspace_name_unique";
DROP INDEX "channel_members_channel_user_unique";
DROP INDEX "attachments_task_idx";
DROP INDEX "activities_created_idx";
DROP INDEX "activities_actor_idx";
DROP INDEX "activities_workspace_idx";
DROP TABLE "workspaces";
DROP TABLE "workspace_members";
DROP TABLE "users";
DROP TABLE "tasks";
DROP TABLE "task_labels";
DROP TABLE "task_assignees";
DROP TABLE "refresh_tokens";
DROP TABLE "projects";
DROP TABLE "notifications";
DROP TABLE "messages";
DROP TABLE "labels";
DROP TABLE "comments";
DROP TABLE "channels";
DROP TABLE "channel_members";
DROP TABLE "attachments";
DROP TABLE "activities";
DROP TYPE "workspace_role";
DROP TYPE "task_priority";
DROP TYPE "notification_type";
DROP TYPE "global_role";
DROP TYPE "channel_type";
