/**
 * The client map is cached against a fingerprint of its inputs, because
 * rebuilding it costs a whole TypeScript program — 7.5s and 1.2 GB on a
 * 1,940-route app.
 *
 * Every failure mode here is silent: the cache either never hits (the feature
 * is dead but nothing says so) or hits when it should not (the frontend types
 * against routes the server no longer serves). Neither shows up without a test.
 *
 * @module @forinda/kickjs-cli/__tests__/client-map-cache.test
 */

import { describe, expect, it, vi } from 'vitest'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { kickClientTypegen } from '../src/typegen/builtin/client'
import type { TypegenContext } from '../src/typegen/plugin'

// Only the resolver is faked — building a real program is the cost this whole
// feature exists to avoid. The fingerprint runs for real, because it is what
// these tests are about: a faked one could not catch the cache hashing its
// own output.
vi.mock('../src/typegen/client/resolve-entries', async (importActual) => {
  const actual = await importActual<typeof import('../src/typegen/client/resolve-entries')>()
  return { ...actual, resolveClientMap: vi.fn(async () => ({})) }
})

const BANNER = '/* AUTO-GENERATED by kick typegen — do not edit. Plugin: kick/client */\n\n'
const OUT = '.kickjs/types/kick__client.d.ts'
const STAMP = '.kickjs/cache/client-map.sha1'

/** A project shaped like one `kick new` scaffolds. */
function project() {
  const dir = mkdtempSync(join(tmpdir(), 'kick-map-cache-'))
  mkdirSync(join(dir, 'src'), { recursive: true })
  writeFileSync(join(dir, 'src', 'a.ts'), 'export const a = 1')
  // The generated tsconfig includes the types directory the map is written to.
  writeFileSync(
    join(dir, 'tsconfig.json'),
    JSON.stringify({ include: ['src', '.kickjs/types/**/*.d.ts'] }),
  )
  return dir
}

/**
 * One `kick typegen` pass.
 *
 * `writeOutput` mirrors the runner, which writes the returned content to disk
 * *after* generate() resolves. Passing false is the failure the stamp has to
 * survive: the plugin ran, but its output never landed.
 */
async function pass(dir: string, { writeOutput = true } = {}) {
  const write = async (rel: string, contents: string) => {
    mkdirSync(join(dir, rel, '..'), { recursive: true })
    writeFileSync(join(dir, rel), contents)
  }
  const ctx = {
    cwd: dir,
    config: { typegen: { client: true } },
    importTs: vi.fn(),
    writeFile: vi.fn(write),
    getScanResult: vi.fn().mockResolvedValue({ routes: [] }),
    log: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
  } as unknown as TypegenContext

  const out = await kickClientTypegen().generate(ctx)
  if (out !== null && writeOutput) await write(OUT, `${BANNER}${out}\n`)
  return out
}

describe('client map cache', () => {
  it('skips a second run that changed nothing', async () => {
    // Regression: the scaffolded tsconfig includes `.kickjs/types/**\/*.d.ts`,
    // which is where this map is written. A fingerprint that hashed it would
    // depend on the previous run's output, never match twice, and leave the
    // cache dead on arrival for every project the CLI generates.
    const dir = project()
    expect(await pass(dir)).not.toBeNull()
    expect(await pass(dir)).toBeNull()
  })

  it('rebuilds after a source file changes', async () => {
    const dir = project()
    await pass(dir)
    writeFileSync(join(dir, 'src', 'a.ts'), 'export const a = 2')
    expect(await pass(dir)).not.toBeNull()
  })

  it('does not skip when the output never made it to disk', async () => {
    // The runner writes the output after generate() returns. A stamp vouching
    // only for the inputs would still match if that write failed, and the
    // stale map would persist with nothing to say so.
    const dir = project()
    await pass(dir, { writeOutput: false })
    expect(await pass(dir)).not.toBeNull()
  })

  it('does not skip when the map has been deleted', async () => {
    const dir = project()
    await pass(dir)
    rmSync(join(dir, OUT))
    expect(await pass(dir)).not.toBeNull()
  })

  it('does not skip when the map was edited after being stamped', async () => {
    const dir = project()
    await pass(dir)
    writeFileSync(join(dir, OUT), `${BANNER}export {} // hand-edited\n`)
    expect(await pass(dir)).not.toBeNull()
  })

  it('writes no stamp under --check, which must not touch the tree', async () => {
    const dir = project()
    const ctx = {
      cwd: dir,
      check: true,
      config: { typegen: { client: true } },
      importTs: vi.fn(),
      writeFile: vi.fn(),
      getScanResult: vi.fn().mockResolvedValue({ routes: [] }),
      log: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
    } as unknown as TypegenContext
    await kickClientTypegen().generate(ctx)
    expect(vi.mocked(ctx.writeFile).mock.calls.map(([rel]) => rel)).not.toContain(STAMP)
  })
})
