/**
 * Overlay scaffolding — project files as real directories instead of TS
 * functions that return strings.
 *
 * A layer is a directory under `packages/cli/templates/` whose `files/`
 * subtree mirrors the project. Layers render in order and a later layer's
 * file replaces an earlier one at the same path.
 *
 * File names: a `_dot_` path segment prefix becomes `.` (`_dot_gitignore` →
 * `.gitignore`), because npm publish drops or rewrites real dotfiles such as
 * `.gitignore` and `.npmrc`.
 *
 * Files that depend on `kick new` options (package.json, the entry file, the
 * env schema, kick.config.ts, README, platform config) are still generated by
 * the functions in `generators/templates/`; they move here as the options
 * they depend on become layers.
 */
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import { dirname, join, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))

/**
 * `packages/cli/templates` — one level above the bundle (`dist/*.mjs`), two
 * above this source file (`src/scaffold/overlay.ts`), so tests can import it
 * from source.
 */
export const TEMPLATES_DIR = [
  join(here, '..', 'templates'),
  join(here, '..', '..', 'templates'),
].find((dir) => existsSync(join(dir, 'base')))!

/** The project path a template file lands at: `_dot_` segment prefixes become `.`. */
export function outputPath(templatePath: string): string {
  return templatePath
    .split('/')
    .map((segment) => (segment.startsWith('_dot_') ? `.${segment.slice(5)}` : segment))
    .join('/')
}

/**
 * Render layers into a map of project-relative path → contents. Pure apart
 * from reading the template directories; the caller decides how to write.
 */
export function renderLayers(
  layers: readonly string[],
  templatesDir: string = TEMPLATES_DIR,
): Map<string, string> {
  const files = new Map<string, string>()
  for (const layer of layers) {
    const root = join(templatesDir, layer, 'files')
    if (!existsSync(root)) throw new Error(`Unknown scaffold layer "${layer}" (${root})`)
    // String entries, not Dirents: `Dirent.parentPath` needs Node 20.12.
    for (const rel of readdirSync(root, { recursive: true, encoding: 'utf-8' }).toSorted()) {
      const abs = join(root, rel)
      if (!statSync(abs).isFile()) continue
      files.set(outputPath(rel.split(sep).join('/')), readFileSync(abs, 'utf-8'))
    }
  }
  return files
}
