/**
 * Standard HTTP status codes as a const enum.
 * Use instead of raw numbers for readability and type safety.
 *
 * @example
 * ```ts
 * throw new HttpException(HttpStatus.NOT_FOUND, 'User not found')
 * ctx.res.status(HttpStatus.CREATED).json(data)
 * ```
 */
export const HttpStatus = {
  // 2xx Success
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  // 3xx Redirection
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  NOT_MODIFIED: 304,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  // 4xx Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  CONFLICT: 409,
  GONE: 410,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,

  // 5xx Server Errors
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const

export type HttpStatusCode = (typeof HttpStatus)[keyof typeof HttpStatus]

/**
 * IANA HTTP status reason phrases for the codes the framework's typed
 * helpers cover. Used as the default `title` when a {@link ProblemException}
 * is constructed without one. Keep in sync with {@link HttpStatus}.
 */
const STATUS_REASONS: Record<number, string> = {
  400: 'Bad Request',
  401: 'Unauthorized',
  402: 'Payment Required',
  403: 'Forbidden',
  404: 'Not Found',
  405: 'Method Not Allowed',
  406: 'Not Acceptable',
  409: 'Conflict',
  410: 'Gone',
  422: 'Unprocessable Entity',
  429: 'Too Many Requests',
  500: 'Internal Server Error',
  501: 'Not Implemented',
  502: 'Bad Gateway',
  503: 'Service Unavailable',
  504: 'Gateway Timeout',
}

/** Validation error detail — shape used by `unprocessable()` and `fromZodError()`. */
export interface ValidationError {
  field: string
  message: string
  code?: string
}

/**
 * RFC 9457 — Problem Details for HTTP APIs.
 * https://datatracker.ietf.org/doc/html/rfc9457
 *
 * Canonical error shape for HTTP responses. Only `status` is required;
 * everything else has a sensible default. Extension members (any other
 * JSON-compatible field) are allowed per §3.2 — pass them on the same
 * object and the framework forwards them through.
 *
 * @example
 * ```ts
 * const problem: ProblemDetails = {
 *   type: 'https://api.example.com/problems/out-of-credit',
 *   status: 403,
 *   title: 'You do not have enough credit',
 *   detail: 'Your balance is 30, but that costs 50.',
 *   instance: '/account/12345/messages/abc',
 *   // extension members per §3.2
 *   balance: 30,
 * }
 * ```
 */
export interface ProblemDetails {
  /**
   * URI reference identifying the problem type. Per §4.2.1, when
   * dereferenced it SHOULD return human-readable documentation. Defaults
   * to `about:blank` when omitted (RFC 9457 §3.1.1).
   */
  type?: string
  /**
   * Short human-readable summary, advisable to be the same regardless of
   * the occurrence (§3.1.4). Defaults to the IANA reason phrase for
   * `status` when omitted.
   */
  title?: string
  /** HTTP status code generated by the origin server. Required. */
  status: number
  /**
   * Human-readable explanation specific to this occurrence (§3.1.5).
   * Per the RFC's safety guidance, do not include sensitive information
   * (tokens, full SQL, stack traces) — those belong in logs.
   */
  detail?: string
  /**
   * URI reference identifying the specific occurrence (§3.1.6).
   * Typically the request path. Adopters set this explicitly — the
   * framework does not auto-populate it to avoid leaking unexpected
   * structure.
   */
  instance?: string
  /**
   * Extension members per §3.2 — any other JSON-compatible field.
   * Common examples: `balance`, `errors`, `traceId`, `accounts`.
   */
  [key: string]: unknown
}

/**
 * Typed HTTP exception with status code, free-form details, and optional
 * response headers. Provides static factory methods for common HTTP errors.
 *
 * `details` is intentionally typed as `unknown` — it serializes straight into
 * the response body's `errors` field, so any JSON-compatible shape works
 * (string, object, array of mixed values, ValidationError[]).
 *
 * `headers` are merged into the response by the global error handler so
 * spec-mandated headers (Retry-After, WWW-Authenticate, Allow, Location)
 * stay on the exception, not on ad-hoc try/catch chains.
 *
 * For RFC 9457 — Problem Details responses, throw {@link ProblemException}
 * instead — the global error handler emits `application/problem+json` for
 * those automatically.
 */
export class HttpException extends Error {
  constructor(
    public readonly status: number,
    message: string,
    public readonly details?: unknown,
    public readonly headers?: Record<string, string>,
  ) {
    super(message)
    this.name = 'HttpException'
  }

  /** Return a new exception with `headers` shallow-merged onto this one. */
  withHeaders(headers: Record<string, string>): HttpException {
    return new HttpException(this.status, this.message, this.details, {
      ...this.headers,
      ...headers,
    })
  }

  /** Create from a Zod error */
  static fromZodError(error: any, message?: string): HttpException {
    const firstIssue = error.issues?.[0]
    const details: ValidationError[] = (error.issues || []).map((issue: any) => ({
      field: issue.path?.join('.') || '',
      message: issue.message,
      code: issue.code,
    }))
    return new HttpException(
      HttpStatus.UNPROCESSABLE_ENTITY,
      message || firstIssue?.message || 'Validation failed',
      details,
    )
  }

  static badRequest(message = 'Bad Request') {
    return new HttpException(HttpStatus.BAD_REQUEST, message)
  }
  static unauthorized(message = 'Unauthorized', wwwAuthenticate?: string) {
    return new HttpException(
      HttpStatus.UNAUTHORIZED,
      message,
      undefined,
      wwwAuthenticate ? { 'WWW-Authenticate': wwwAuthenticate } : undefined,
    )
  }
  static forbidden(message = 'Forbidden') {
    return new HttpException(HttpStatus.FORBIDDEN, message)
  }
  static notFound(message = 'Not Found') {
    return new HttpException(HttpStatus.NOT_FOUND, message)
  }
  static methodNotAllowed(allowedMethods: string[], message = 'Method Not Allowed') {
    return new HttpException(HttpStatus.METHOD_NOT_ALLOWED, message, undefined, {
      Allow: allowedMethods.join(', '),
    })
  }
  static conflict(message = 'Conflict') {
    return new HttpException(HttpStatus.CONFLICT, message)
  }
  static unprocessable(message = 'Unprocessable Entity', details?: ValidationError[]) {
    return new HttpException(HttpStatus.UNPROCESSABLE_ENTITY, message, details)
  }
  static tooManyRequests(message = 'Too Many Requests', retryAfterSeconds?: number) {
    return new HttpException(
      HttpStatus.TOO_MANY_REQUESTS,
      message,
      undefined,
      retryAfterSeconds !== undefined ? { 'Retry-After': String(retryAfterSeconds) } : undefined,
    )
  }
  static serviceUnavailable(message = 'Service Unavailable', retryAfterSeconds?: number) {
    return new HttpException(
      HttpStatus.SERVICE_UNAVAILABLE,
      message,
      undefined,
      retryAfterSeconds !== undefined ? { 'Retry-After': String(retryAfterSeconds) } : undefined,
    )
  }
  static internal(message = 'Internal Server Error') {
    return new HttpException(HttpStatus.INTERNAL_SERVER_ERROR, message)
  }
}

/**
 * Default `title` for an RFC 9457 problem with the given status — the IANA
 * reason phrase, or `'Error'` for codes outside the framework's table.
 * Exposed so {@link ProblemException} construction and {@link RequestContext}'s
 * `problem` helpers share a single source of truth.
 */
export function defaultProblemTitle(status: number): string {
  return STATUS_REASONS[status] ?? 'Error'
}

/**
 * Exception that carries an RFC 9457 — Problem Details payload. When
 * thrown, the framework error handler emits `application/problem+json`
 * with the canonical shape; `type` defaults to `about:blank`, `title`
 * to the IANA reason phrase for `status`.
 *
 * For adopters who want the problem fields required at construction
 * (vs. {@link HttpException}'s optional shape), this is the typed
 * entry point. The static factories pre-fill `status` and `title` for
 * the common codes.
 *
 * @example
 * ```ts
 * throw new ProblemException({
 *   type: 'https://api.example.com/problems/out-of-credit',
 *   status: 403,
 *   title: 'You do not have enough credit',
 *   detail: 'Your balance is 30, but that costs 50.',
 *   instance: '/account/12345/messages/abc',
 *   balance: 30,  // extension
 * })
 *
 * // Or via the static factory:
 * throw ProblemException.forbidden({
 *   type: 'https://api.example.com/problems/out-of-credit',
 *   detail: 'Your balance is 30, but that costs 50.',
 *   balance: 30,
 * })
 * ```
 */
export class ProblemException extends HttpException {
  public readonly problem: ProblemDetails

  constructor(problem: ProblemDetails, headers?: Record<string, string>) {
    const title = problem.title ?? defaultProblemTitle(problem.status)
    const detail = problem.detail ?? title
    super(problem.status, detail, undefined, headers)
    this.name = 'ProblemException'
    this.problem = { ...problem, title }
  }

  /** Return a new exception with `headers` shallow-merged onto this one. */
  withHeaders(headers: Record<string, string>): ProblemException {
    return new ProblemException(this.problem, { ...this.headers, ...headers })
  }

  /** 400 Bad Request with optional detail / instance / extensions. */
  static badRequest(input: Omit<ProblemDetails, 'status'> = {}): ProblemException {
    return new ProblemException({ status: 400, ...input })
  }
  /** 401 Unauthorized. Pass a `WWW-Authenticate` challenge via the headers arg. */
  static unauthorized(
    input: Omit<ProblemDetails, 'status'> = {},
    wwwAuthenticate?: string,
  ): ProblemException {
    return new ProblemException(
      { status: 401, ...input },
      wwwAuthenticate ? { 'WWW-Authenticate': wwwAuthenticate } : undefined,
    )
  }
  /** 403 Forbidden. */
  static forbidden(input: Omit<ProblemDetails, 'status'> = {}): ProblemException {
    return new ProblemException({ status: 403, ...input })
  }
  /** 404 Not Found. */
  static notFound(input: Omit<ProblemDetails, 'status'> = {}): ProblemException {
    return new ProblemException({ status: 404, ...input })
  }
  /** 405 Method Not Allowed. Pass the allowed methods so the Allow header is set. */
  static methodNotAllowed(
    allowedMethods: string[],
    input: Omit<ProblemDetails, 'status'> = {},
  ): ProblemException {
    return new ProblemException({ status: 405, ...input }, { Allow: allowedMethods.join(', ') })
  }
  /** 409 Conflict. */
  static conflict(input: Omit<ProblemDetails, 'status'> = {}): ProblemException {
    return new ProblemException({ status: 409, ...input })
  }
  /**
   * 422 Unprocessable Entity. Pass per-field issues via the `errors`
   * extension — keep the array shape per the RFC's recommended convention
   * (`{ field, message, code }`).
   */
  static unprocessable(input: Omit<ProblemDetails, 'status'> = {}): ProblemException {
    return new ProblemException({ status: 422, ...input })
  }
  /** 429 Too Many Requests. Pass `retryAfterSeconds` to set the Retry-After header. */
  static tooManyRequests(
    input: Omit<ProblemDetails, 'status'> = {},
    retryAfterSeconds?: number,
  ): ProblemException {
    return new ProblemException(
      { status: 429, ...input },
      retryAfterSeconds !== undefined ? { 'Retry-After': String(retryAfterSeconds) } : undefined,
    )
  }
  /** 503 Service Unavailable. */
  static serviceUnavailable(
    input: Omit<ProblemDetails, 'status'> = {},
    retryAfterSeconds?: number,
  ): ProblemException {
    return new ProblemException(
      { status: 503, ...input },
      retryAfterSeconds !== undefined ? { 'Retry-After': String(retryAfterSeconds) } : undefined,
    )
  }
  /** 500 Internal Server Error. */
  static internal(input: Omit<ProblemDetails, 'status'> = {}): ProblemException {
    return new ProblemException({ status: 500, ...input })
  }

  /**
   * Build from a Zod error — 422 with the issues serialized into the
   * `errors` extension per RFC 9457 §3.2's array convention.
   */
  static fromZodError(error: any, input: Omit<ProblemDetails, 'status'> = {}): ProblemException {
    const issues: ValidationError[] = (error.issues || []).map((issue: any) => ({
      field: issue.path?.join('.') || '',
      message: issue.message,
      code: issue.code,
    }))
    return new ProblemException({
      status: 422,
      detail: error.issues?.[0]?.message,
      ...input,
      errors: issues,
    })
  }
}

/**
 * Normalize an RFC 9457 problem into the wire shape — fill in `type` →
 * `'about:blank'` and `title` → IANA reason phrase. The same function is
 * used by {@link RequestContext}'s `problem` helpers and the global
 * error handler so the response is identical regardless of entry point.
 */
export function normalizeProblem(input: ProblemDetails): ProblemDetails {
  return {
    type: input.type ?? 'about:blank',
    title: input.title ?? defaultProblemTitle(input.status),
    ...input,
  }
}
