import path from 'node:path'
import { readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'

import { computeMigrationHash } from './journal'
import type { Journal } from './journal'

export interface ReviewResult {
  id: string
  /** True when the migration was already reviewed (no-op). */
  alreadyReviewed: boolean
}

/**
 * Mark a migration as reviewed: flip `meta.json.reviewed` to `true` —
 * the ONLY review state the runner checks. The SQL files carry an
 * immutable provenance banner (`-- Generated by @forinda/kickjs-db vX`),
 * so reviewing never touches them and the journal hash stays valid.
 *
 * Legacy migrations (generated before the banner) still carry mutable
 * `-- REVIEWED: false` markers inside the hashed files; for those we
 * keep the old behaviour — swap the markers and recompute the journal
 * hash so all three stay in sync.
 */
export async function reviewMigration(migrationsDir: string, id: string): Promise<ReviewResult> {
  const dir = path.join(migrationsDir, id)
  const metaPath = path.join(dir, 'meta.json')
  if (!existsSync(metaPath)) {
    throw new Error(`kickjs-db: migration '${id}' not found under ${migrationsDir}`)
  }

  const meta = JSON.parse(await readFile(metaPath, 'utf8')) as { reviewed?: boolean }
  if (meta.reviewed === true) {
    return { id, alreadyReviewed: true }
  }

  // 1. Legacy marker migration: swap `-- REVIEWED: false` if present.
  //    New-style files (immutable banner) are left untouched.
  let sqlChanged = false
  for (const file of ['up.sql', 'down.sql']) {
    const p = path.join(dir, file)
    if (!existsSync(p)) continue
    const sql = await readFile(p, 'utf8')
    const next = sql.replace(/^-- REVIEWED: false$/m, '-- REVIEWED: true')
    if (next !== sql) {
      await writeFile(p, next, 'utf8')
      sqlChanged = true
    }
  }

  // 2. Flip the gate in meta.json (the value the runner actually checks).
  meta.reviewed = true
  await writeFile(metaPath, JSON.stringify(meta, null, 2) + '\n', 'utf8')

  // 3. Journal hash follows only when the hashed bytes changed (legacy
  //    marker swap). Banner-style migrations skip this entirely.
  if (sqlChanged) {
    const journalPath = path.join(migrationsDir, '_journal.json')
    const journal = JSON.parse(await readFile(journalPath, 'utf8')) as Journal
    const entry = journal.entries.find((e) => e.id === id)
    if (entry) {
      entry.hash = await computeMigrationHash(dir)
      await writeFile(journalPath, JSON.stringify(journal, null, 2) + '\n', 'utf8')
    }
  }

  return { id, alreadyReviewed: false }
}
